"""Corrections of the ebook text (proof-reading of books 11-15): applied by bk_extract.items(), so the typeset text, the
fidelity counts of bk_report and the font subsets all see the corrected text.

FIXES[scratch] = list of (part, old, new, note)
    part   part number (int) or '*' for every part of the book
    old    literal text (may run across inline runs of one paragraph) -- or re.compile(...) for a pattern
    new    replacement (a pattern's replacement may use \\1 ...)
    note   short reason, listed in docs/16k/corrections.md
A literal fix that matches nothing is reported by bk_report (fix_unused), so a fix can never silently go stale.
"""
import re

CJK = '㐀-䶿\u4e00-\u9fff'
_PUNCT = '，。、；：？！“”‘’（）《》〈〉「」『』…'
# A single em dash between two non-digit characters, one of them Chinese: the ebook's rendering of the Chinese dash '——'
# (ranges such as 1990—2000 or 19世纪—20世纪 keep the single dash; GB/T 15834 uses it as the connector).
DASH1 = re.compile(r'(?<=[%s%s])—(?![—\d])|(?<![—\d])—(?=[%s%s])' % (CJK, _PUNCT, CJK, _PUNCT))

# books whose cross-references point at <span id=…> anchors (captured as link targets)
SPAN_ANCHORS = {'q15': r'^jz_\d+_\d+$'}
SPECIAL = ('MOVE', 'RENUM', 'SHIFT', 'SPLIT', 'PGNO', 'RELINK', 'ADDMARK', 'NOTEBACK', 'HEAD', 'HREF', 'ANCHOR')   # mark/structure fixes (not text replacements)

ASCII_COMMA = re.compile(r'(?<=[%s）”])\s?,\s?(?=[%s“（])' % (CJK, CJK))
ASCII_COLON = re.compile(r'(?<=[%s）])\s?:\s?(?=[%s“（])' % (CJK, CJK))

FIXES = {
    'q11': [
        (8, 'RELINK', '我认为，大国总在寻找机会攫取超出其对手的权力', '1', '1', 'part0008#chapter8-ft1', 'part0008#chapter8-fn1',
         '注释：第二章注码1误链到注2，改正'),
    ],
    'q12': [
        (1, 'Wil Walluchow', 'Wil Waluchow', '人名拼寫：Waluchow'),
        (2, '在效力上的的先後順序', '在效力上的先後順序', '多字：「的」重複'),
        (2, '因此規則身即具有不確定性', '因此規則本身即具有不確定性', '漏字：本身'),
        (2, '或者是由法院地宣告納粹法律', '或者是由法院宣告納粹法律', '多字：「地」'),
        (2, '與道德有沒有關係？。', '與道德有沒有關係？', '標點：問號後多餘句號'),
        (2, '這個概念被用來只法體系時', '這個概念被用來指法體系時', '錯字：指'),
        (2, '對義務規範強制直形的規範', '對義務規範強制執行的規範', '錯字：執行'),
        (3, 'H.L.A.Hart', 'H. L. A. Hart', '排版：縮寫間缺空格'),
        (4, '修改地支離破碎', '修改得支離破碎', '用字：得'),
        (4, '在前面提過的校定原則下', '在前面提過的校訂原則下', '用字：校訂'),
        (8, '『公權利機關』', '『公權力機關』', '錯字：公權力（同段下文作「公權力機關」）'),
        (10, '為什麼法律未必反應被管治的群體', '為什麼法律未必反映被管治的群體', '錯字：反映'),
        (10, 'PGNO', '它們就會變成法律。xxxix'),
        (10, '好像被綁架而必須付出贖金。」）〔131〕）', '好像被綁架而必須付出贖金。」〔131〕）', '標點：括號不配對'),
        (11, 'PGNO', '研究什麼。它走自己的路。xlvi'),
        (11, 'PGNO', '法理學顯得重要。xlvii'),
        (10, '26 H. L. A. Hart, ‘Positivism and the Separation', 'H. L. A. Hart, ‘Positivism and the Separation', '注釋：多餘的「26」（英文版注號殘留）'),
        (11, '或者更有企圖心地，變成一種成預測', '或者更有企圖心地，變成一種預測', '多字：成'),
        (11, '它能夠深化我們理瞭解', '它能夠深化我們的理解', '錯字：的理解'),
        (11, '是「沒什麼用的 」', '是「沒什麼用的」', '排版：多餘空格'),
        (11, '就像他的朋友以薩．柏林（Isaiah Berlin', '就像他的朋友以薩．柏林（Isaiah Berlin）', '標點：漏右括號'),
        (11, ' ，哈特認為善就是不能化約的多元', '，哈特認為善就是不能化約的多元', '排版：多餘空格'),
        (11, '那種約化一元論', '那種化約一元論', '用字：化約（與上文「不能化約」一致）'),
        (12, '並沒有多少學述引註', '並沒有多少學術引註', '錯字：學術'),
        (12, 'the TwoLevel Theory', 'the Two-Level Theory', '注釋：漏連字號'),
        ('*', 'Law and Modern Mind', 'Law and the Modern Mind', '注釋：書名漏 the'),
        (15, '為什麼它們合而為要求一個對法律的定義', '為什麼它們合起來引發了對法律下定義的要求', '語病：together they prompt the demand for a definition'),
        (15, 'non fuerit’:St. Augustine', 'non fuerit’: St. Augustine', '注釋：缺空格'),
        (15, '就此法理論家們意見分歧的，', '就此法理論家們意見分歧，', '多字：的'),
        (15, '《遺囑法》的「真正推定條款」（innocent-seeming provision）', '《遺囑法》的「看似無害的條款」（innocent-seeming provision）', '誤譯：innocent-seeming 是「看似無害的」'),
        (15, '25th Anniversary Essay’,2005', '25th Anniversary Essay’, 2005', '注釋：缺空格'),
        (16, '認為一般性的語言能夠以此種方式來定義', '認為一般性的語詞能夠以此種方式來定義', '用字：general terms（語詞）'),
        (16, '被定義之語言所意指的共同特質', '被定義之語詞所意指的共同特質', '用字：語詞'),
        (16, '這個具形容詞作用的語言的用法', '這個具形容詞作用的語詞的用法', '用字：語詞'),
        (16, '除了我們討論過得簡單的傳統形式', '除了我們討論過的簡單的傳統形式', '錯字：的'),
        (16, 'Hart,‘Definition and Theory in Jurisprudence, ’70 LQR', 'Hart, ‘Definition and Theory in Jurisprudence’, 70 LQR', '注釋：引號與逗號錯位'),
        (16, 'Theory and Definition in Jurisprudence,’PAS', 'Theory and Definition in Jurisprudence’, PAS', '注釋：引號與逗號錯位'),
        (16, '於「法」這個詞語的定義，參閱', '關於「法」這個詞語的定義，參閱', '漏字：關'),
        (16, '‘The Nature of Law\'載於', '‘The Nature of Law’載於', '注釋：右引號'),
        (16, 'Arguments, 1945;Austin', 'Arguments, 1945; Austin', '注釋：缺空格'),
        (16, '此為德沃金刺論證（Semantic Sting Argument）', '此為德沃金語義之刺論證（Semantic Sting Argument）', '漏字：語義之刺'),
        (18, '在《法理學之確定範圍》（Jurisprudence Determined）', '在《法理學之確定範圍》（The Province of Jurisprudence Determined）', '書名：英文書名不全'),
        (18, '而如果被指示者保持不動，就能夠避開危險的時候', '而如果被指示者保持不動，就能夠避開危險的時候。', '標點：段末漏句號'),
        (18, '（gave an order ）', '（gave an order）', '排版：多餘空格'),
        (18, '就因為奧斯丁對對號令', '就因為奧斯丁對號令', '多字：對'),
        (18, '‘The Logic of IMperatives’', '‘The Logic of Imperatives’', '注釋：大小寫'),
        (18, 'What is Value?, 1952, chap. 6 ;', 'What is Value?, 1952, chap. 6;', '注釋：多餘空格'),
        (18, 'Grice,‘Meaning’', 'Grice, ‘Meaning’', '注釋：缺空格'),
        (18, '各種祈使語氣的共同內涵—意欲他人', '各種祈使語氣的共同內涵——意欲他人', '標點：破折號'),
        (18, '我們這麼是出於方便的原因', '我們這麼做是出於方便的原因', '漏字：做'),
        ('*', re.compile(r'’\s?,\s?(?=\d{4})'), '’, ', '注釋：引號後逗號與年份間空格錯位'),
        ('*', re.compile(r'(?<=[A-Za-z.]),‘'), ', ‘', '注釋：逗號後缺空格'),
        (19, 'Lecture 22, 5th edn., p444', 'Lecture 22, 5th edn., p.444', '注釋：頁碼漏點'),
        (19, '（前引書., pp.14,16）', '（前引書，pp.14, 16）', '注釋：標點'),
        (19, 'in Medlden, Essays in Moral Philosophy', 'in Melden, Essays in Moral Philosophy', '注釋：人名拼寫 Melden'),
        (19, '那就是國會才識主權的擁有者', '那就是國會才是主權的擁有者', '錯字：是'),
        (19, '我們會詳細遞檢視', '我們會詳細地檢視', '錯字：地'),
        (19, 'Some Myth about Positivism', 'Some Myths about Positivism', '注釋：篇名 Myths'),
        (21, '這樣的分類雖然稍嫌租略', '這樣的分類雖然稍嫌粗略', '錯字：粗略'),
        (21, '對謀殺著施加特定制裁', '對謀殺者施加特定制裁', '錯字：者'),
        (21, '這兩者皆以太高的代價來，即它們將', '這兩者皆付出了太高的代價，即它們將', '語病：漏動詞'),
        (21, '而課稅卻沒有這樣的意含', '而課稅卻沒有這樣的意涵', '用字：意涵'),
        (21, '授予司法權利之規則與課予法官義務之附加規則', '授予司法權力之規則與課予法官義務之附加規則', '錯字：權力'),
        (21, 'Schedule III, Part5, 5', 'Schedule III, Part 5, 5', '注釋：缺空格'),
        (21, 'A. M. Honore, ‘Real Laws’', 'A. M. Honoré, ‘Real Laws’', '注釋：人名拼寫（與前言一致）'),
        (21, '（1976）71 American Journal of Jurisprudence 21', '（1976）21 American Journal of Jurisprudence 71', '注釋：卷號與頁碼互倒（AJJ 第21卷，1976年，第71頁）'),
        (22, '去做這些語詞只是他去做的事', '去做這些語詞指示他去做的事', '錯字：指示'),
        (23, '未能通過「合理的」的檢驗', '未能通過「合理性」的檢驗', '用字：合理性'),
        (23, '他們並非要求人們去做某些事，而是授予權力給他們；他們並不課予義務', '它們並非要求人們去做某些事，而是授予權力給他們；它們並不課予義務', '代詞：指法律用「它們」'),
        (23, '‘Some Myth about Positivism’', '‘Some Myths about Positivism’', '注釋：篇名 Myths'),
        (23, 'Hägerström, Inquires into', 'Hägerström, Inquiries into', '注釋：拼寫 Inquiries'),
        (24, '‘Some Myth about Positivism’', '‘Some Myths about Positivism’', '注釋：篇名 Myths'),
        (25, '此種立法權威的社會實踐基礎，簡單直接之行為規則', '此種立法權威的社會實踐基礎，與簡單直接之行為規則', '漏字：與'),
        (25, 'Legal Theory’ inAndrei Marmor', 'Legal Theory’ in Andrei Marmor', '注釋：缺空格'),
        (25, '以及第六章第二節頁。', '以及第六章第二節。', '多字：頁'),
        (26, '一九九四年英國有一位婦人被控告', '一九四四年英國有一位婦人被控告', '史實：R. v. Duncan 案在1944年（括號內判例年份即1944）'),
        (26, '而不允計執行其二', '而不允許執行其二', '錯字：允許'),
        ('*', '係爭', '系爭', '用字：系爭'),
        (27, '邊泌主張最高的權力可以被「明白之傳統」（express convention）限制，而且違反傳統所制定', '邊沁主張最高的權力可以被「明示協約」（express convention）限制，而且違反協約所制定', '錯字：邊沁；誤譯：convention 此處指協約'),
        (27, 'Parliamentary Sovereignty and the Common-wealth', 'Parliamentary Sovereignty and the Commonwealth', '注釋：書名拼寫'),
        (28, '國王貴族（the Kings Peers）', '國王、貴族（the King, Peers）', '誤譯：國王與貴族並列'),
        (28, '其通常通常立法機構', '其通常立法機構', '多字：通常'),
        (28, '7 Howard 1 12 L. Ed. 581', '7 Howard 1, 12 L. Ed. 581', '注釋：漏逗號'),
        (28, '（參閱上註111）', '（參閱上註108）', '互見錯誤：討論「類的描述」的是註108'),
        (30, '強制性性命令', '強制性命令', '多字：性'),
        (30, '為了要調合立法行為', '為了要調和立法行為', '用字：調和'),
        (31, '伴隨違規行而來之敵對反應', '伴隨違規行為而來之敵對反應', '漏字：為'),
        (31, '生活中發揮作為規則發揮功能的方式', '生活中作為規則發揮功能的方式', '多字：發揮'),
        (31, 'The Structure of Stairs Institute', 'The Structure of Stair’s Institutions', '注釋：書名 Stair’s Institutions'),
        (31, 'chaps.i & ii,;', 'chaps. i & ii;', '注釋：標點'),
        (31, '26 Philosophy,1951', '26 Philosophy, 1951', '注釋：缺空格'),
        (31, 'Cambridge Law Journal ,1959', 'Cambridge Law Journal, 1959', '注釋：空格錯位'),
        (31, '反動', '反應', '用字：reaction 譯「反應」（「反動」有其他含義）'),
        (31, '以即本身接受規則之人', '以及本身接受規則之人', '錯字：以及'),
        (31, '29 PAS Suppl. vol., 1955 , pp.247-50', '29 PAS Suppl. vol., 1955, pp.247-50', '注釋：空格錯位'),
        (32, '刻於某公共石碑上的一分權威性規則', '刻於某公共石碑上的一份權威性規則', '錯字：一份'),
        (32, '相反地，他們以進一步的次級規則來補充', '相反地，它們以進一步的次級規則來補充', '代詞：指法體系用「它們」'),
        (34, '前面一種陳述我們稱為內部陳述（internal statement）因為', '前面一種陳述我們稱為內部陳述（internal statement），因為', '標點：漏逗號'),
        (34, 'General Theory, pp.110-24,131-4', 'General Theory, pp.110-24, 131-4', '注釋：缺空格'),
        (34, 'American Journal of Internaitonal Law', 'American Journal of International Law', '注釋：拼寫'),
        (34, '至少模糊了，本書所強調的要點', '至少模糊了本書所強調的要點', '標點：多餘逗號'),
        (34, 'chap. 1 and 2, 哈特的批評', 'chap. 1 and 2；哈特的批評', '標點：中文分句'),
        (35, '所有政府部分的實踐情形', '所有政府部門的實踐情形', '錯字：部門'),
        (35, 'especially p.189. and Marshall', 'especially p.189; and Marshall', '注釋：標點'),
        (35, 'Meldon edn. 1958', 'Melden ed., 1958', '注釋：人名拼寫 Melden'),
        (36, '（或者較坦白的說法是；「被視為」）', '（或者較坦白的說法是：「被視為」）', '標點：冒號'),
        (36, '（1952, I TLR 1245）', '（1952, 1 TLR 1245）', '注釋：卷號1誤為I（同第四章）'),
        (36, 'nella Scienza del Diritto,1960', 'nella Scienza del Diritto, 1960', '注釋：缺空格'),
        (36, 'The Law and the Commonwealth,1949', 'The Law and the Commonwealth, 1949', '注釋：缺空格'),
        (36, 'Dixon, ‘ The Law and the Constitution’', 'Dixon, ‘The Law and the Constitution’', '注釋：多餘空格'),
        (38, '在類似脈絡中反覆出現事例', '在類似脈絡中反覆出現的事例', '漏字：的'),
        (38, '至目前為止，我們把開放文本', '至目前為止，我們把開放性結構', '譯名統一：open texture 全書譯「開放性結構」（譯注亦指出不應譯「開放文本」）'),
        (38, '法律的開放文本意味著', '法律的開放性結構意味著', '譯名統一：開放性結構'),
        (38, '但同時也是盲目地解決問題解，', '但同時也是盲目地解決問題，', '多字：解'),
        (38, '無論其很明顯地屬於或部屬於「公平費率」或「安全系統」', '無論其很明顯地屬於或不屬於「公平費率」或「安全體系」', '錯字：不屬於；譯名統一：安全體系'),
        (38, '衡量各種未被預期到社會目標', '衡量各種未被預期到的社會目標', '漏字：的'),
        (38, '（Harvard University Press, 1986v, chap. 5', '（Harvard University Press, 1985）, chap. 5', '注釋：出版年1985，右括號誤為v'),
        (38, 'Oxford University Press,1991', 'Oxford University Press, 1991', '注釋：缺空格'),
        (38, 'Honore在74 LQR', 'Honoré在74 LQR', '注釋：人名拼寫'),
        (38, 'US v. Carroll Towing Co.,1947', 'US v. Carroll Towing Co., 1947', '注釋：缺空格'),
        (38, 'Dickinson, op. cit., p.146-50', 'Dickinson, op. cit., pp.146-50', '注釋：頁碼範圍用 pp.'),
        (38, '（rev, edn., Oxford University Press, 1994）', '（rev. edn., Oxford University Press, 1994）', '注釋：標點'),
        (38, 'Precedent in English Law,1961', 'Precedent in English Law, 1961', '注釋：缺空格'),
        (39, '我們在第三章中已經詳細地檢討過', '我們在第五章中已經詳細地檢討過', '互見錯誤：對義務之預測理論的檢討在第五章第二節'),
        (39, '僅僅紀錄和預測法院的決定', '僅僅記錄和預測法院的決定', '用字：記錄'),
        (39, 'The Bramble Bush, 2nd end., p.9', 'The Bramble Bush, 2nd edn., p.9', '注釋：edn.'),
        (39, '一是純粹偶然地與規則一致地行為', '一是純粹偶然地與規則一致的行為', '錯字：的'),
        (39, '將棋子推到正確位子的動作', '將棋子推到正確位置的動作', '用字：位置'),
        (39, 'Some Rationalism about Realism’載於：43 Yale Law Review', 'Some Rationalism about Realism’載於：43 Yale Law Journal', '注釋：刊名 Yale Law Journal'),
        (39, '[ fin de siecle]', '[fin de siècle]', '注釋：多餘空格；法文重音'),
        (39, '‘The Judgement Intuitive’ ;‘The Function of the “Hunch” in Judicial Decision’', '‘The Judgment Intuitive: The Function of the “Hunch” in Judicial Decision’', '注釋：篇名誤拆為二'),
        ('*', '那麼樣就算是得分', '那樣就算是得分', '多字：麼'),
        (40, '構成了判斷兩者正確與否之的標準', '構成了判斷兩者正確與否的標準', '多字：之'),
        (40, 'Charles Evan Hughes and the Supreme Court', 'Charles Evans Hughes and the Supreme Court', '注釋：人名 Evans'),
        (40, '在The Defence Court of the United States', '在The Supreme Court of the United States', '注釋：書名誤植（Hughes 著 The Supreme Court of the United States）'),
        (41, '可以由法院解來解決', '可以由法院來解決', '多字：解'),
        (41, '而且也免於他自己先前立法的拘束', '而且也免於它自己先前立法的拘束', '代詞：指機構用「它」'),
        (41, '相反地，他應該擁有此項更為廣泛', '相反地，它應該擁有此項更為廣泛', '代詞：指國會用「它」'),
        (41, '在效果上這兩範疇是相互重疊的', '在效果上這兩個範疇是相互重疊的', '漏字：個'),
        (41, '將某些國會權力非不可撤銷地授予女皇和下議院', '將某些國會權力非不可撤銷地授予女王和下議院', '用字：女王（全書一致）'),
        (41, '如果國會真的這樣透過立法來自殺，他可能會同時', '如果國會真的這樣透過立法來自殺，它可能會同時', '代詞：指國會用「它」'),
        (41, '難道他不能結束他在某些議題上的立法權力', '難道它不能結束它在某些議題上的立法權力', '代詞：指國會用「它」'),
        (41, '這種說法不止如同尚基（Sankey）議員所說', '這種說法不只如同尚基（Sankey）勳爵所說', '誤譯：Lord Sankey 是勳爵（時任大法官），非議員'),
        (41, 'Limits of Legal Chang’', 'Limits of Legal Change’', '注釋：漏字母'),
        (41, '在沒有自制領同意之情形下', '在沒有自治領同意之情形下', '錯字：自治領'),
        (41, 'The Statute of Westminister', 'The Statute of Westminster', '注釋：拼寫'),
        (42, '（juge, gendarme et legislateur）', '（juge, gendarme et législateur）', '注釋：法文重音'),
        (42, '（《懺悔錄，卷四》）', '（《上帝之城》，卷四）', '出處錯誤：此語出自奧古斯丁《上帝之城》第四卷，不是《懺悔錄》'),
        (43, '禁止有色人種到公園去法律是不義的', '禁止有色人種到公園去的法律是不義的', '漏字：的'),
        (43, '會變成不義的，如果他們因為膚色', '會變成不義的，如果它們因為膚色', '代詞：指法律用「它們」'),
        (43, '（Nicomachean Ethics, Books, chaps1-3）', '（Nicomachean Ethics, Book V, chaps. 1-3）', '注釋：卷次漏 V'),
        (43, 'Sidgwick, The Method of Ethics', 'Sidgwick, The Methods of Ethics', '注釋：書名 Methods'),
        (43, 'Denise Reaume, ‘Is Integrity a Virtue?', 'Denise Réaume, ‘Is Integrity a Virtue?', '注釋：人名拼寫（與三版序一致）'),
        (43, '（Leviathan, chap30）', '（Leviathan, chap. 30）', '注釋：格式'),
        (43, 'Lecture VI, p. 260 n.,）', 'Lecture VI, p. 260 n.）', '注釋：多餘逗號'),
        (43, '關於嚴格責任和詐欺罪中的替代責任（vicarious liability）的討論', '關於侵權法中的嚴格責任和替代責任（vicarious liability）的討論', '誤譯：in tort（侵權法），非「詐欺罪」'),
        (43, 'The Criminal Law, chap7;', 'The Criminal Law, chap. 7;', '注釋：格式'),
        (43, 'chap.10 , Law as a Leap of Faith', 'chap. 10, Law as a Leap of Faith', '注釋：空格錯位'),
        (44, '它們不要求什麼重大的犧牲：他們不會為了要求服從而施加重大壓力，而如果不遵守或是改變了這些規則，對於社會生活也不會什麼重大的變化', '它們不要求什麼重大的犧牲：它們不會為了要求服從而施加重大壓力，而如果不遵守或是改變了這些規則，對於社會生活也不會有什麼重大的變化', '代詞；漏字：有'),
        (44, '不能用這種方式去更加或廢除', '不能用這種方式去更改或廢除', '錯字：更改'),
        (44, '區分道德和所其他社會規範形式', '區分道德和所有其他社會規範形式', '漏字：有'),
        (44, '由法律所造成傳統和道德之改變', '由法律所造成的傳統和道德之改變', '漏字：的'),
        (44, '我們剛剛才強調過的，，蘊藏在', '我們剛剛才強調過的，蘊藏在', '標點：重複逗號'),
        (44, 'Essays on Moral Philosophy, Melden ed. ; Whitley, ‘On Defining “Morality”, in', 'Essays on Moral Philosophy, Melden ed.; Whitley, ‘On Defining “Morality”’, in', '注釋：多餘空格；漏右引號'),
        (44, 'The Definition of Law, pp. 43-51, 對此的批評', 'The Definition of Law, pp. 43-51；對此的批評', '標點：中文分句'),
        (44, 'Holmes, The Common Law, Lecture 11;', 'Holmes, The Common Law, Lecture II;', '注釋：講次為羅馬數字 II'),
        (44, '關於自殺的法律中對此的區分', '關於殺人罪的法律中對此的區分', '誤譯：law of homicide（殺人罪）'),
        (44, '‘A Plea for Excuses’, 57 PAS, 956-7', '‘A Plea for Excuses’, 57 PAS, 1956-7', '注釋：年份漏1'),
        (45, '會被迫以無法反映現實方式', '會被迫以無法反映現實的方式', '漏字：的'),
        (45, '特別在是宗教的辯論或實踐', '特別是在宗教的辯論或實踐', '語序'),
        (45, 'Social Principles of the Democratic State', 'Social Principles and the Democratic State', '注釋：書名 and'),
        (47, '認為理性可以發現正確行為的原的主張', '認為理性可以發現正確行為的原則的主張', '漏字：則'),
        (47, '奠基在「法則」的這語詞的單純歧義性', '奠基在「法則」這個語詞的單純歧義性', '語病'),
        (47, '《法意》（Espirit des Lois）', '《法意》（Esprit des Lois）', '注釋：法文拼寫'),
        (47, '他們隱然假設著，生存是人類行為的本有目的', '它們隱然假設著，生存是人類行為的本有目的', '代詞：指思考模式用「它們」'),
        (47, '即使活得在悲慘可憐', '即使活得悲慘可憐', '多字：在'),
        (47, 'Quaestiones 90-7 ; Grotius, On the Law of War and Peace; Proleomena', 'Quaestiones 90-7; Grotius, On the Law of War and Peace; Prolegomena', '注釋：多餘空格；拼寫 Prolegomena'),
        (47, 'at 601 n. 25.。', 'at 601 n. 25。', '標點：重複句點'),
        (47, 'Philip Soper ‘Some Confusions', 'Philip Soper, ‘Some Confusions', '注釋：漏逗號'),
        (47, 'ss. I-6', 'ss. 1-6', '注釋：數字1誤為I'),
        (48, '如果沒有者些規定', '如果沒有這些規定', '錯字：這些'),
        (48, '（包括皮骨骼或甲殼）', '（包括外骨骼或甲殼）', '錯字：外骨骼（exoskeleton）'),
        (48, '總是會有人既托蔽於它', '總是會有人既託庇於它', '錯字：託庇'),
        (48, '而是強得他們太多', '而是強過他們太多', '錯字：強過'),
        (48, '而侵犯他人傾向如果沒有得到控制', '而侵犯他人的傾向如果沒有得到控制', '漏字：的'),
        (48, '創造義務的規則的成為必要的因素', '創造義務的規則成為必要的因素', '多字：的'),
        (48, '不只是作為服從的動機，而已也是個保證', '不只是作為服從的動機，而且也是個保證', '錯字：而且'),
        (48, '甚至有反得其害的危險', '甚至有反受其害的危險', '用字：反受其害'),
        (48, '即使他們沒有任何制裁機構', '即使它沒有任何制裁機構', '代詞：指體系用「它」'),
        (49, '震聾發聵', '振聾發聵', '錯字：振聾發聵'),
        (49, '可能基礎許多不同的考量', '可能基於許多不同的考量', '錯字：基於'),
        (49, '而被會混淆', '而被混淆', '多字：會'),
        (49, '就像我們在第六章裡所看到的，在法律的開放性結構裡', '就像我們在第七章裡所看到的，在法律的開放性結構裡', '互見錯誤：開放性結構在第七章第一節'),
        (49, '不可否認他們卻也長久存在著', '不可否認它們卻也長久存在著', '代詞：指法體系用「它們」'),
        (49, 'The Province of Jurisprudence Defined', 'The Province of Jurisprudence Determined', '書名：Determined'),
        (49, '27 July, 1945, Oberlandesgericht Bamberg, 5 Söddeutsche Juristen-Zeitung', '27 July, 1949, Oberlandesgericht Bamberg, 5 Süddeutsche Juristen-Zeitung', '史實：班堡高等法院判決在1949年；刊名 Süddeutsche'),
        (49, "H. L. A. Hart, Legal Positivism and the Separation of Law and Morals', 71 Harvard L. Rev.", 'H. L. A. Hart, ‘Positivism and the Separation of Law and Morals’, 71 Harvard L. Rev.', '注釋：篇名及引號'),
        (49, 'L. Fuller,’Positivism and Fidelity to Law，同前揭', 'L. Fuller, ‘Positivism and Fidelity to Law’，同前揭', '注釋：引號'),
        (49, '裝飾地好像是對一般違法行為的懲罰', '裝飾得好像是對一般違法行為的懲罰', '用字：得'),
        (49, '73 HLR I, p. 960', '73 HLR 1, 1959', '注釋：卷期與年份（Wechsler 文載 73 HLR 1，1959年）'),
        (49, '對於的討論見 The Lectures', '對此的討論見 The Lectures', '漏字：此'),
        (49, 'Principles of Crimninal Law', 'Principles of Criminal Law', '注釋：拼寫'),
        (49, '某個婦人被控在一九三年的納粹時期告發她的先生', '某個婦人被控在一九四四年的納粹時期告發她的先生', '年份殘缺：告發發生在1944年'),
        (49, '班堡州高等法院於一九四九年六月的判決', '班堡州高等法院於一九四九年七月的判決', '史實：判決日為1949年7月27日（正文所引）'),
        (49, '這個解最近受到質疑', '這個解釋最近受到質疑', '漏字：釋'),
        (49, '帕普博士的批評很有見的', '帕普博士的批評很有見地', '錯字：見地'),
        (51, '並且重新思考他們就何種層面而言是必要的', '並且重新思考它們就何種層面而言是必要的', '代詞：指關係用「它們」'),
        (51, '因為初級與次級原則的結合', '因為初級與次級規則的結合', '錯字：規則'),
        (52, '（理由已在第三章詳述）', '（理由已在第五章詳述）', '互見錯誤：對義務之預測分析的批判在第五章第二節'),
        (52, '當然，團結為和平解決方案是否能證明', '當然，「聯合一致共策和平」決議（Uniting for Peace Resolution）是否能證明', '誤譯：resolution 指聯合國大會決議'),
        (52, 'and ‘ The Reality of International Law’ , 118 Foreign Affairs', 'and ‘The Reality of International Law’, 18 Foreign Affairs', '注釋：多餘空格；卷號為18'),
        (53, '因此除了他們自己外不受任何法律限制', '因此除了它們自己外不受任何法律限制', '代詞：指國家用「它們」'),
        (53, 'Chapters on Current International pp. 11-16', 'Chapters on Current International Law, pp. 11-16', '注釋：書名漏 Law'),
        (53, 'et la droit internationale', 'et le droit international', '注釋：法文冠詞與性數'),
        (53, 'op. cit.,345 ff.; Strarke', 'op. cit., 345 ff.; Starke', '注釋：缺空格；人名拼寫'),
        (54, '這會是很具啟發性見解', '這會是很具啟發性的見解', '漏字：的'),
        (54, '國際法與國內法這種的形式上的差異', '國際法與國內法這種形式上的差異', '多字：的'),
        (54, '不同在國際法規則之下', '不同於在國際法規則之下', '漏字：於'),
        (54, '其他可能的規則也可以運作地一樣好', '其他可能的規則也可以運作得一樣好', '用字：得'),
        (54, '如我們在第七章所見，是很荒謬的', '如我們在第八章所見，是很荒謬的', '互見錯誤：道德不能由立法改變的討論在第八章第二節'),
        (54, '我們曾在第五章批評過這個論點', '我們曾在第九章批評過這個論點', '互見錯誤：此論點的批評在第九章第三節'),
        (54, '某些特定的規則與可以與道德發生衝突', '某些特定的規則可以與道德發生衝突', '多字：與'),
        (54, 'The Base of Obligation in International Law', 'The Basis of Obligation in International Law', '注釋：書名 Basis'),
        (55, '我們可以會問它們的歷史起源', '我們可以問它們的歷史起源', '多字：會'),
        (55, '即使有國際法院第三十八條之規定', '即使有國際法院規約第三十八條之規定', '漏字：規約（Statute of the ICJ, Art. 38）'),
        (56, '〔編著：後記注釋中以引號標示者為編者所加。〕', '〔編按：後記注釋中以方括號標示者為編者所加。〕', '錯字：編按；編者注用方括號〔〕標示（見註257、271等）'),
        (56, '1776-1976’ , 51 New York University Law Review', '1776-1976’, 51 New York University Law Review', '注釋：空格錯位'),
        (57, '是否存在不同類型的法律規則嗎？', '是否存在不同類型的法律規則？', '語病：是否……嗎'),
        (57, '41 Stanford Law Review 871,1989', '41 Stanford Law Review 871, 1989', '注釋：缺空格'),
        (57, 'Contemporary Jurisprudence,1983', 'Contemporary Jurisprudence, 1983', '注釋：缺空格'),
        (58, '每個人都公平地獲得了的警告', '每個人都公平地獲得了警告', '多字：的'),
        (58, '這項法律的主要功能失靈時候', '這項法律的主要功能失靈的時候', '漏字：的'),
        (58, '〔LE 93. 〕', '〔LE 93.〕', '注釋：多餘空格'),
        (59, '德沃金說法的預設著', '德沃金的說法預設著', '語序：的說法'),
        (59, '勝過了規範遺囑效果的制定法條文，一個謀殺被繼承人的繼承人', '勝過了規範遺囑效果的制定法條文，因此一個謀殺被繼承人的繼承人', '漏字：因此（so as to deny a murderer the right to inherit）'),
        (59, '161 A.2d69', '161 A.2d 69', '注釋：缺空格'),
        (60, '艾特金法官（Lord Atkins）在「唐納修訴史帝文森」（Donoghue v. Stevensen）', '艾特金法官（Lord Atkin）在「唐納修訴史帝文森」（Donoghue v. Stevenson）', '人名、案名拼寫：Lord Atkin；Donoghue v. Stevenson'),
        (60, '這些原則分別在不同情境下建立起注意義務', '這些規則分別在不同情境下建立起注意義務', '誤譯：distinct rules establishing a duty of care'),
        (60, '以及各種法律淵源間的優越、從屬關係先辨別出來', '以及各種法律淵源間的優越、從屬關係辨別出來', '多字：「先」重複'),
        (60, 'A.C. 562 .', 'A.C. 562.', '注釋：多餘空格'),
        (60, 'RDCJ p3 at 16', 'RDCJ p.3 at 16', '注釋：頁碼格式'),
        (60, '‘ Negative and Positive Positivism’', '‘Negative and Positive Positivism’', '注釋：多餘空格'),
        (60, 'D Lyons, ‘ Principles, Positivism and Legal Theory’', 'D. Lyons, ‘Principles, Positivism and Legal Theory’', '注釋：縮寫點；多餘空格'),
        (60, 'LE 47,67.', 'LE 47, 67.', '注釋：缺空格'),
        (60, 'LE401.', 'LE 401.', '注釋：缺空格'),
        (61, '因它完全與我所認為，法律可以被鑑別而無須訴諸道德的主張完全相容', '因它與我所認為，法律可以被鑑別而無須訴諸道德的主張完全相容', '多字：「完全」重複'),
        (61, '並且為他們的證立提供最佳的理由', '並且為它們的證立提供最佳的理由', '代詞：指法律用「它們」'),
        (61, 'RDCJ,260.', 'RDCJ 260.', '注釋：多餘逗號'),
        (61, 'RDCJ,259.', 'RDCJ 259.', '注釋：多餘逗號'),
        (62, '可以經由其社會淵源被鑑別出來既定法律', '可以經由其社會淵源被鑑別出來的既定法律', '漏字：的'),
        (62, '荷姆斯法官（Oliver Wendell Homles）', '荷姆斯法官（Oliver Wendell Holmes）', '人名拼寫：Holmes'),
        (62, '為當下的疑難案件中指出確定的答案', '為當下的疑難案件指出確定的答案', '多字：中'),
        (62, '對於這項批評可以有很多回答。我認為，法官之所以', '對於這項批評可以有很多回答。第一，我認為法官之所以', '結構：與下文「第二」呼應'),
        (62, 'cf.LE 37-9', 'cf. LE 37-9', '注釋：缺空格'),
        (63, 'The Province of Jurisprudence Determined ed. Hart', 'The Province of Jurisprudence Determined, ed. Hart', '縮寫表：缺逗號'),
        (63, 'Kelsen,General Theory', 'Kelsen, General Theory', '縮寫表：缺空格'),
        (64, '一九二九年以第一名的優異成績畢業', '一九二九年以一等榮譽（first-class honours）的優異成績畢業', '誤譯：first 指一等榮譽學位，非第一名'),
        (64, '一九五二年，古哈特（A.L. Goodhart）辭去「牛津大學法理學講座」。一九五三年，哈特被選為該講座的繼任者，並且在同年五月三十日發表就職講演', '一九五一年，古哈特（A.L. Goodhart）辭去「牛津大學法理學講座」。一九五二年，哈特被選為該講座的繼任者，並且在一九五三年五月三十日發表就職講演', '史實：古哈特1951年轉任大學學院院長，哈特1952年當選法理學教授，就職講演在1953年5月30日（見附錄二1953年條）'),
        (64, '（Positivism and Separation of Law and Morals）', '（Positivism and the Separation of Law and Morals）', '篇名：漏 the'),
        (64, '在一場又一場的論戰中渡過', '在一場又一場的論戰中度過', '用字：度過'),
        (64, '〈哈特的法律理論—從法概念', '〈哈特的法律理論——從法概念', '標點：破折號'),
        (64, '〈道德、法律與社群—哈特與德弗林的辯論〉', '〈道德、法律與社群——哈特與德弗林的辯論〉', '標點：破折號'),
        (64, 'Juan Ramn de Pramo, “Harts Concept of Law nach dreißig Jahren. Ein Interview mit dem Autor,” Rechhtstheorie 22', 'Juan Ramón de Páramo, “Hart’s ‘Concept of Law’ nach dreißig Jahren. Ein Interview mit dem Autor,” Rechtstheorie 22', '注釋：人名變音符、撇號、刊名拼寫'),
        (65, '19481', '1948', '年份：多一位數字'),
        (65, 'vii, p75, and author', 'vii, 75 pp., and author', '頁數格式'),
        (65, 'x, p.271.', 'x, 271 pp.', '頁數格式'),
        (65, ', p.54 The Lionel Cohen Lectures, Tenth Series, Hebrew University, Jerusalem, 1964." Changing', ', 54 pp. The Lionel Cohen Lectures, Tenth Series, Hebrew University, Jerusalem, 1964. "Changing', '頁數格式；引號錯位'),
        (65, 'Law and the Modern Mind 6th printing, in Mind, 60 :268-270', 'Law and the Modern Mind, 6th printing, in Mind, 60:268-270', '缺逗號；多餘空格'),
        (65, 'Weidenfeld & Nicholson', 'Weidenfeld & Nicolson', '出版社名拼寫：Nicolson'),
        (65, 'Inquiries into the Nature of Law and Moral,', 'Inquiries into the Nature of Law and Morals,', '書名：Morals'),
        (65, 'Anthony M. Honore', 'Anthony M. Honoré', '人名變音符'),
        (65, 'Richard A. Wasserstorm', 'Richard A. Wasserstrom', '人名拼寫'),
        (65, 'Punishment and Elimination of Responsibility（London', 'Punishment and the Elimination of Responsibility（London', '書名：漏 the（見1968年條第VII篇）'),
        (65, 'P.A. Norstedt & Soner', 'P.A. Norstedt & Söner', '出版社名變音符'),
        (65, 'Barbara Wooton', 'Barbara Wootton', '人名拼寫'),
        (65, 'ed. Bikhu Parekh', 'ed. Bhikhu Parekh', '人名拼寫（見1962年條）'),
        (65, 'in Encyclopedia Britannica, 14th edn.', 'in Encyclopaedia Britannica, 14th edn.', '書名拼寫'),
        (65, '(see at 1988, below）', '(see at 1988, below)', '括號不配對'),
        (65, 'Praktika Tes Akademias Athehon', 'Praktika Tes Akademias Athenon', '刊名拼寫'),
        (65, 'El neuvo desafio al positivismo juridico', 'El nuevo desafío al positivismo jurídico', '西文篇名拼寫與重音'),
        (65, 'Juan Ramon de Paramo', 'Juan Ramón de Páramo', '人名重音'),
        (65, 'under the title “Hart’s Concept of Law’ nach dreisig Jahren”, Rechtstheorie 22', 'under the title “Hart’s ‘Concept of Law’ nach dreißig Jahren,” Rechtstheorie 22', '引號不配對；德文 dreißig'),
        (65, 'with Tony Honoré 2nd edn.', 'with Tony Honoré, 2nd edn.', '缺逗號'),
        (65, '“Commemt,”', '“Comment,”', '拼寫：Comment'),
        (65, 'J.O. Urmson & Jonathan Ree', 'J.O. Urmson & Jonathan Rée', '人名變音符'),
        (65, 'Dorfrecht: Kluwer', 'Dordrecht: Kluwer', '地名拼寫：Dordrecht'),
        (65, re.compile(r'Social Science(?!s)'), 'Social Sciences', '書名：Social Sciences'),
        (65, re.compile(r'(?<=[^\u4e00-\u9fff（(])\s*（([^（）()\u4e00-\u9fff]*)[）)]'), r' (\1)', '排版：西文書目用半形括號'),
        (65, re.compile(r'[”"]\s?,\s?(?=\d{4})'), ',” ', '排版：引號、逗號與年份'),
        (65, re.compile(r'(?:^|(?<=[\s(\[]))"'), '“', '排版：西文直引號改彎引號'),
        (65, re.compile(r'"'), '”', '排版：西文直引號改彎引號'),
        (65, re.compile(r"(?<=[A-Za-z])'(?=[A-Za-z])"), '’', '排版：撇號'),
        (65, re.compile(r'(?<=[\w.]),(?=[A-Za-z\d])'), ', ', '排版：逗號後缺空格'),
        (65, re.compile(r'(?<=[A-Za-z]) ,'), ',', '排版：逗號前多餘空格'),
        (65, re.compile(r'(?<=\d)：(?=\d)'), ':', '排版：全形冒號'),
        (65, re.compile(r'(?<=\d)pp\.'), ' pp.', '排版：頁數缺空格'),
        (65, re.compile(r'\bp\.(\s?)(?=\d+-\d+)'), r'pp.\1', '排版：頁碼範圍用 pp.'),
        (65, re.compile(r'\b(vol|no|nos)\.(?=\d)'), r'\1. ', '排版：卷期缺空格'),
        ('*', '意含', '意涵', '用字：意涵'),
        ('*', re.compile(r'(?<=[\u4e00-\u9fff]) (?=[\u4e00-\u9fff])'), '', '排版：漢字間多餘空格'),
        (15, '在英國沒有規則說每個人必須或應當或應該每週去看電影，這也不是真實的；真實的是每週規律地去看電影的人潮', '說在英國有一項規則規定每個人必須或應當或應該每週去看電影，這並不是真實的；真實的只是人們每週規律地去看電影', '誤譯：雙重否定使意思相反（原意：並沒有這樣的規則，只有規律的行為）'),
        ('*', '所要補充的的第一項特徵', '所要補充的第一項特徵', '多字：「的」重複'),
        ('*', '在邊緣處所具有的的性質', '在邊緣處所具有的性質', '多字：「的」重複'),
        ('*', '關於法律鑑別的的基本承認規則', '關於法律鑑別的基本承認規則', '多字：「的」重複'),
        ('*', re.compile(r'(?<=[，。；：、])[ ]+(?=[\u4e00-\u9fff「（])'), '', '排版：全形標點後多餘空格'),
        ('*', re.compile(r'(?<=[\u4e00-\u9fff]) (?=「)'), '', '排版：引號前多餘空格'),
        ('*', re.compile(r'(?<=[0-9A-Za-z.]),(?=(?:1[89]|20)\d\d\b)'), ', ', '注釋：逗號與年份間缺空格'),
    ],
    'q13': [
        (range(3, 14), DASH1, '——', '标点：电子书把破折号“——”都排成了单个“—”（578处），一律恢复为“——”；数字间的连接号不动'),
        (range(3, 14), re.compile(r'(?<=\d)~(?=\d)'), '～', '标点：数字范围的半角“~”改为“～”'),
        # copyright page: the ebook lower-cased most Latin capitals
        (1, '（ciP）', '（CIP）', '版权页：电子书把拉丁字母大写误转为小写，恢复（下同）'),
        (1, '图书馆ciP数据', '图书馆CIP数据', '版权页大小写'),
        (1, 'What’s the Right thing to Do?', 'What’s the Right Thing to Do?', '版权页大小写（两处）'),
        (1, 'isBN 978–7–5086–3623–8', 'ISBN 978-7-5086-3623-8', '版权页大小写；ISBN 用连字符（两处）'),
        (1, 'i. ①公… ii. ①桑… ②朱… iii. ①伦理学', 'Ⅰ. ①公… Ⅱ. ①桑… ②朱… Ⅲ. ①伦理学', '版权页：CIP 分类序号为罗马数字'),
        (1, 'Michael J. sandel', 'Michael J. Sandel', '版权页大小写（两处）'),
        (1, 'copyright © 2009', 'Copyright © 2009', '版权页大小写'),
        (1, 'simplified chinese translation copyright © 2011 by china citic Press',
         'Simplified Chinese translation copyright © 2011 by China CITIC Press', '版权页大小写'),
        (1, 'international creative Management, inc.', 'International Creative Management, Inc.', '版权页大小写'),
        (1, 'Bardon-chinese', 'Bardon-Chinese', '版权页大小写'),
        (1, 'ALL RiGHts ReseRVeD', 'ALL RIGHTS RESERVED', '版权页大小写'),
        (1, '（china citic Press）', '（China CITIC Press）', '版权页大小写'),
        (1, '（citic Publishing Group）', '（CITIC Publishing Group）', '版权页大小写'),
        # chapter 1
        (3, '以至于大多数经济学家干脆不予理会。索维尔在', '以至于大多数经济学家干脆不予理会。”索维尔在', '标点：引文缺后引号'),
        (3, '对于反价格欺诈者们的愤慨', '对于价格欺诈者们的愤慨', '多字：愤慨的对象是价格欺诈者（the outrage at price gougers）'),
        (3, '法律是否应当在各种德性观念保持中立', '法律是否应当在各种德性观念之间保持中立', '漏字：在……之间'),
        (3, '（有些是纳税人资助的人寿保险公司）', '（有些靠纳税人的资助才得以维持）',
         '误译：原文 some of them on taxpayer-funded life support，指靠纳税人资金“维持生命”，不是“人寿保险公司”'),
        (3, '成为政府助救的日常用语', '成为政府救助的日常用语', '错字（倒文）：助救→救助'),
        (3, '从自由地角度考量公正', '从自由的角度考量公正', '错字：地→的'),
        (3, '奥萨姆·本·拉登', '奥萨马·本·拉登', '错字：通行译名“奥萨马”'),
        (3, '固定成形，非理性思考能改变', '固定成形，非理性思考所能改变', '漏字：意为“不是理性思考所能改变的”，缺“所”则意思相反'),
        (3, 'Joseph B Treaster', 'Joseph B. Treaster', '注释：英文缩写点脱落（下同）'),
        (3, 'August 18, 2004, pA1;', 'August 18, 2004, p. A1;', '注释：缩写点脱落'),
        (3, 'at wwwcapmagcom/articleasp? ID=3918', 'at www.capmag.com/article.asp?ID=3918', '注释：网址中的点脱落'),
        (3, 'Tyler E Boudreau', 'Tyler E. Boudreau', '注释：缩写点脱落'),
        (3, 'S Mitra Kalita', 'S. Mitra Kalita', '注释：缩写点脱落'),
        (3, '见杰克德·桑蒂斯（Jake DeSantis）', '见杰克·德桑蒂斯（Jake DeSantis）', '注释：人名音译断错（Jake DeSantis）'),
        (3, '与杰克德·桑蒂斯不同', '与杰克·德桑蒂斯不同', '注释：同上'),
        (3, '参议员夏洛特·布朗在这里引证了', '参议员夏洛德·布朗在这里引证了', '注释：与正文译名“夏洛德·布朗”统一'),
        (3, '参议员格拉斯里在爱荷华州的WMT电台', '参议员格拉斯利在艾奥瓦州的WMT电台', '注释：与正文译名“格拉斯利”“艾奥瓦州”统一'),
        (3, 'William D Cohen', 'William D. Cohen', '注释：缩写点脱落'),
        (3, 'David R Francis', 'David R. Francis', '注释：缩写点脱落'),
        (3, 'Marcy 9, 2009', 'March 9, 2009', '注释：月份拼错（Marcy→March）'),
        (3, '.Ibid.', 'Ibid.', '注释：多余的点'),
        # chapter 2
        (4, '被政府和公司普遍采用决策形式', '被政府和公司普遍采用的决策形式', '漏字：的'),
        (4, '交换其他物品和便利设施做法', '交换其他物品和便利设施的做法', '漏字：的'),
        (4, '功利主义的逻辑。他们认为，“如果男子留宿', '功利主义的逻辑。她们认为，“如果男子留宿', '错字：指学院里的年长女教员，他们→她们'),
        (4, '他３岁学希腊语，８岁学拉丁语', '他3岁学希腊语，8岁学拉丁语', '排版：全角数字混入'),
        (4, '即，源于痛苦的快乐和自由是唯一值得追求的目标', '即，快乐和免于痛苦是唯一值得追求的目标',
         '误译：密尔原文 pleasure, and freedom from pain, are the only things desirable as ends'),
        (4, '事物值得拥有的唯一标准就是人们想要他。', '事物值得拥有的唯一标准就是人们想要它。', '错字：指事物，他→它'),
        (4, 'H. L. A Hart, eds.', 'H. L. A. Hart, eds.', '注释：缩写点脱落（下同）'),
        (4, 'John Bowring, ed, The Works', 'John Bowring, ed., The Works', '注释：缩写点脱落'),
        (4, 'Ursula K Le Guin', 'Ursula K. Le Guin', '注释：缩写点脱落'),
        (4, 'Arthur D Little International', 'Arthur D. Little International', '注释：缩写点脱落'),
        (4, 'Philip-Morris-Czech-Studyhtm', 'Philip-Morris-Czech-Study.htm', '注释：网址中的点脱落'),
        (4, 'pmczechstudypdf', 'pmczechstudy.pdf', '注释：网址中的点脱落'),
        (4, 'July 22, 2001, P. D7.', 'July 22, 2001, p. D7.', '注释：页码缩写应小写'),
        (4, '(Cal.Ct. App.1981) The cost-benefit', '(Cal.Ct. App.1981). The cost-benefit', '注释：句末缺点'),
        (4, 'Safety Issues,“ Washington Post', 'Safety Issues,” Washington Post', '注释：后引号误为前引号'),
        (4, 'W. Kip Kiscusi', 'W. Kip Viscusi', '注释：作者名拼错（W. Kip Viscusi）'),
        (4, 'E.P.A Drops the', 'E.P.A. Drops the', '注释：缩写点脱落'),
        # chapter 3: the ebook doubled mark [77] and lost [88]-[90]; every later mark linked one note too early
        (5, 'RELINK', '弗里德曼基于同样的理由反对最低工资制度', '[77]', '[78]', 'part0005#note78f', 'part0005#note78', '注释：注码错位，改为[78]'),
        (5, 'RELINK', '行业执照的要求也错误地干涉', '[78]', '[79]', 'part0005#note79f', 'part0005#note79', '注释：注码错位，改为[79]'),
        (5, 'RELINK', '在《无政府、国家与乌托邦》一书中', '[79]', '[80]', 'part0005#note80f', 'part0005#note80', '注释：注码错位，改为[80]'),
        (5, 'RELINK', '诺齐克反对模式化的公正理论', '[80]', '[81]', 'part0005#note81f', 'part0005#note81', '注释：注码错位，改为[81]'),
        (5, 'RELINK', '由于很多人热切地想看乔丹打球', '[81]', '[82]', 'part0005#note82f', 'part0005#note82', '注释：注码错位，改为[82]'),
        (5, 'RELINK', '那么，向乔丹的收入征税到底错在何处', '[82]', '[83]', 'part0005#note83f', 'part0005#note83', '注释：注码错位，改为[83]'),
        (5, 'RELINK', '获取某个人的劳动成果等同于', '[83]', '[84]', 'part0005#note84f', 'part0005#note84', '注释：注码错位，改为[84]'),
        (5, 'RELINK', '允许买卖肾器官的一个理由', '[84]', '[85]', 'part0005#note85f', 'part0005#note85', '注释：注码错位，改为[85]'),
        (5, 'RELINK', '2007年，79岁的医生杰克·凯沃金', '[85]', '[86]', 'part0005#note86f', 'part0005#note86', '注释：注码错位，改为[86]'),
        (5, 'RELINK', '2001年，在德国罗滕堡的一个村庄', '[86]', '[87]', 'part0005#note87f', 'part0005#note87', '注释：注码错位，改为[87]'),
        (5, 'ADDMARK', '当迈维斯被押受审时', '法庭将迈维斯判为过失杀人并判处八年半的有期徒刑，试图以此来解决这一难题。', '[88]', 'part0005#note88f', 'part0005#note88', '注释：正文漏排注码[88]，补上'),
        (5, 'ADDMARK', '当迈维斯被押受审时', '上诉法院推翻了这一过于宽大的判决，并将迈维斯判为终身监禁。', '[89]', 'part0005#note89f', 'part0005#note89', '注释：正文漏排注码[89]，补上'),
        (5, 'ADDMARK', '当迈维斯被押受审时', '因为他认为工厂化农业经营太不人道了。', '[90]', 'part0005#note90f', 'part0005#note90', '注释：正文漏排注码[90]，补上'),
        (5, 'NOTEBACK', '[87]', 'part0005#note87', '注释：注[87]的返回链接断开，接回'),
        (5, 'NOTEBACK', '[88]', 'part0005#note88', '注释：注[88]的返回链接断开，接回'),
        (5, 'NOTEBACK', '[89]', 'part0005#note89', '注释：注[89]的返回链接断开，接回'),
        (5, 'NOTEBACK', '[90]', 'part0005#note90', '注释：注[90]的返回链接断开，接回'),
        (4, 'Stefan Collini, ed (Cambridge', 'Stefan Collini, ed. (Cambridge', '注释：缩写点脱落'),
        # chapter 3
        (5, '即使是在一个经济较弱的州，成为一个亿万富翁', '即使是在一个经济较弱的年份，成为一个亿万富翁', '误译：福布斯400强是全国榜单，原意是“即使在经济不景气的年份”'),
        (5, '所造成的伤害与跟它对接受者的帮助一样多', '所造成的伤害与它对接受者的帮助一样多', '多字：与跟→与'),
        (5, '阑尾切割手术', '阑尾切除手术', '用词错误：appendectomy 是阑尾切除术'),
        (5, '而非法获得土地或其他资产呢？', '而非法获得土地或其他资产的影响呢？', '漏字：“受到……的影响”句子残缺'),
        (5, '出现在密歇根的一个监狱，因为他八年来一直给那些身患绝症的、想死的病人提供致命性的药物。',
         '走出密歇根的一所监狱，此前他因给那些身患绝症的、想死的病人提供致命性的药物而服刑八年。',
         '误译：凯沃金是2007年服刑八年后获释出狱（emerged from a Michigan prison），不是“出现在监狱”“八年来一直提供药物”'),
        (5, '除了新奥尔良州和华盛顿州之外', '除了俄勒冈州和华盛顿州之外', '事实错误：当时允许医助自杀的是俄勒冈州和华盛顿州（新奥尔良是城市）'),
        (5, '似乎是自由至上主义哲学的一次书面申请', '似乎是自由至上主义哲学的一次教科书式的应用', '误译：textbook application 是“教科书式的应用”，不是“书面申请”'),
        (5, '400 list08_cx_mn_0917richam-ericans_land.html', '400list08_cx_mn_0917richamericans_land.html', '注释：网址被断开'),
        (5, 'Lawrence Michel, Jared Bernstein', 'Lawrence Mishel, Jared Bernstein', '注释：作者名拼错（Lawrence Mishel）'),
        (5, 'www.stateof workingamerica.org', 'www.stateofworkingamerica.org', '注释：网址中多空格'),
        (5, 'concentration. 2004.5.pdf', 'concentration.2004.5.pdf', '注释：网址中多空格'),
        (5, 'Manslaughter,”New York Times', 'Manslaughter,” New York Times', '注释：缺空格'),
        (5, 'Veggie,”Scottish', 'Veggie,” Scottish', '注释：缺空格'),
        (5, 'HEAD', '反驳3：迈克尔·乔丹并非单独作战', 4, '排版：“反驳1”“反驳2”是小标题，“反驳3—5”却排成了正文，统一为小标题'),
        (5, 'HEAD', '反驳4：并不是真的没有经过乔丹本人的同意', 4, '排版：同上'),
        (5, 'HEAD', '反驳5：乔丹很幸运', 4, '排版：同上'),
        # chapter 4
        (6, '最著名的是1863年6月纽约市的征兵暴乱', '最著名的是1863年7月纽约市的征兵暴乱', '事实错误：纽约征兵暴乱发生在1863年7月13—16日'),
        (6, '审判员并不只是投票', '陪审员并不只是投票', '错字：上下文讲的是陪审员'),
        (6, '时，并不真正自愿的，因为她并没有得到充分的信息', '时，并不是真正自愿的，因为她并没有得到充分的信息', '漏字：是'),
        (6, '引发了一个与条件有关问题', '引发了一个与条件有关的问题', '漏字：的'),
        (6, '伊曼努尔·康德', '伊曼纽尔·康德', '译名统一：全书作“伊曼纽尔”'),
        (6, '在选择代孕者时“更加具有歧视性”', '在选择代孕者时“更加挑剔”', '误译：more discriminating 指挑选得更精细，不是“歧视”'),
        (6, 'ADDMARK', '然而，这种全球化的怀孕外包同样也凸显了', '我现在比我怀自己的孩子的时候还要小心。”', '[151]', 'part0006#note151f', 'part0006#note151',
         '注释：正文漏排注码[151]（注151“Ibid.”承注150，指多蒂娅的这句话），补上'),
        (6, 'NOTEBACK', '[151]', 'part0006#note151', '注释：注[151]的返回链接断开，接回'),
        (6, 'James M McPherson', 'James M. McPherson', '注释：缩写点脱落（下同）'),
        (6, 'Geary, We Need. Men', 'Geary, We Need Men', '注释：书名中多点'),
        (6, 'Jeffrey M Jones', 'Jeffrey M. Jones', '注释：缩写点脱落'),
        (6, 'document.php? id=532', 'document.php?id=532', '注释：网址中多空格'),
        (6, 'David M Kennedy', 'David M. Kennedy', '注释：缩写点脱落（两处）'),
        (6, 'Peter W Singer', 'Peter W. Singer', '注释：缩写点脱落'),
        (6, '截止到2008年4月', '截至2008年4月', '用词：表示“到某时为止”用“截至”'),
        (6, 'March Hosenball', 'Mark Hosenball', '注释：作者名拼错（Mark Hosenball）'),
        (6, 'Elizabeth S Anderson', 'Elizabeth S. Anderson', '注释：缩写点脱落'),
        (6, 'Debora L Spar', 'Debora L. Spar', '注释：缩写点脱落'),
        (6, '丝芭自此成为伯纳德学院的院长', '斯帕自此成为伯纳德学院的院长', '注释：译名与正文“斯帕”统一'),
        # chapter 5
        (7, '他发表了第一本著作', '他发表了第一部重要著作', '事实错误：《纯粹理性批判》是康德第一部重要著作（his first major work），此前他已出版多部著作'),
        (7, '纽约商业促进进会', '纽约商业促进会', '多字：促进进会→促进会'),
        (7, '商业改进局经常会在《纽约时报》上', '商业促进会经常会在《纽约时报》上', '译名统一：同段前后作“商业促进会”（Better Business Bureau）'),
        (7, '将理性称为“对欲望的寻求”', '将理性称为“欲望的侦察兵”', '误译：霍布斯称思想为欲望的“侦察兵”（scout for the desires）'),
        (7, '都是与绝对命令想抵触的', '都是与绝对命令相抵触的', '错字：想→相'),
        (7, '可是它们都不是真实的。', '可是它们仍然是真实的。',
         '误译（意思反了）：这些客套话与善意的谎言一样会让人误会，但仍是真话（下文即以“真实而具有误导性的表达”与谎言对照）'),
        (7, '而这位共和党的检察官和克林顿的辩护人', '而这位共和党的国会议员和克林顿的辩护人', '误译：英格利斯是国会议员（上文“一名共和党的国会议员”），不是检察官'),
        (7, '一个带有令人困惑的偏执的社会契约', '一个带有令人困惑的转折的社会契约', '误译：a puzzling twist 是“令人困惑的转折”，不是“偏执”'),
        (7, 'Hackettt Publishing', 'Hackett Publishing', '注释：出版社名多一个t'),
        (7, 'James W Ellington', 'James W. Ellington', '注释：缩写点脱落'),
        # chapter 6
        (8, '只有那些自然公民', '只有那些入籍公民', '误译：宣誓效忠宪法才获得公民身份的是入籍公民（naturalized citizens），“自然公民”意思正相反'),
        (8, 'RENUM', -1, lambda n: 'part0008' if n <= 224 else 'part0009', '{part}#note{n}f', 'part0008#note{n}',
         '注释：第六章全部注码比注文大1（如洛克“默认同意”一句标成了注200《正义论》），整章减1，链接随之改正'),
        (8, 'NOTEBACK', '[199]', 'part0008#note199', '注释：注[199]的返回链接断开，接回'),
        (9, 'RENUM', -2, lambda n: 'part0009', '{part}#note{n}f', 'part0009#note{n}',
         '注释：第七章全部注码比注文大2（如霍普伍德案事实标成了注227），整章减2，链接随之改正'),
        (9, 'NOTEBACK', '[225]', 'part0009#note225', '注释：注[225]的返回链接改指第七章'),
        (9, 'NOTEBACK', '[226]', 'part0009#note226', '注释：注[226]的返回链接断开，接回'),
        (8, '包括意识自由和思想自由的权利', '包括良心自由和思想自由的权利', '误译：liberty of conscience 是“良心自由”'),
        (8, '因为他们根据出生的偶然性来分配收入', '因为它们根据出生的偶然性来分配收入', '代词：指“这些体制”，他们→它们'),
        (8, '他们保证公民们能够得到平等的基本自由', '它们保证公民们能够得到平等的基本自由', '代词：指“市场社会”，他们→它们'),
        (8, '约翰·罗伯特（John Robert）', '约翰·罗伯茨（John Roberts）', '人名错误：美国首席大法官 John Roberts'),
        (8, '首席大法官罗伯特高出100倍', '首席大法官罗伯茨高出100倍', '人名：同上'),
        (8, 'PS. Atiyah', 'P. S. Atiyah', '注释：作者名缩写'),
        (8, '(New York: Oxford University Press, 1979; also', '(New York: Oxford University Press, 1979); also', '注释：缺右括号'),
        (8, 'sAt考试（scholastic Assessment test）', 'SAT考试（Scholastic Assessment Test）', '译注：大小写误转'),
        # chapter 7
        (9, '得克萨斯州立大学法学院运用了', '得克萨斯大学法学院运用了', '名称错误：霍普伍德申请的是得克萨斯大学（University of Texas）法学院，上文即作“得克萨斯大学法学院”'),
        (9, '迈克尔·夏洛特（Michael Charlot），是当时得克萨斯州立大学法学院的主任',
         '迈克尔·沙洛特（Michael Sharlot），是当时得克萨斯大学法学院的院长', '注释：人名、校名与正文统一（Michael Sharlot，得克萨斯大学法学院院长）'),
        (9, '罗纳德·德沃金（Ronald Dwokin）', '罗纳德·德沃金（Ronald Dworkin）', '人名拼错：Dworkin'),
        (9, '在反歧视行为政策中运用民族偏好', '在反歧视行动政策中运用民族偏好', '术语统一：affirmative action 全书作“反歧视行动”'),
        (9, '“斯韦特诉佩因特案” （1950）', '“斯韦特诉佩因特案”（1950）', '排版：多余空格'),
        (9, 'William A Honan', 'William A. Honan', '注释：缩写点脱落'),
        (9, 'Michael J Sandel, Liberalism', 'Michael J. Sandel, Liberalism', '注释：缩写点脱落'),
        (9, '杰弗逊·莫里（ Jefferson Morley ）', '杰弗逊·莫里（Jefferson Morley）', '注释：多余空格'),
        # chapter 8
        (10, '“建立政党是为了什么？”', '“建立城邦是为了什么？”', '误译：亚里士多德问的是城邦（政治共同体）的目的，不是“政党”'),
        (10, '否则，一种政党就沦为一个单纯的联盟', '否则，一种政治联合就沦为一个单纯的联盟', '误译：同上（political association）'),
        (10, '以上两者都忽视了政党的最高目的', '以上两者都忽视了政治联合的最高目的', '误译：同上'),
        (10, '也就是达到这一目的手段', '也就是达到这一目的的手段', '漏字：的'),
        (10, '安东宁·斯科利亚（Antonin Scalia）', '安东宁·斯卡利亚（Antonin Scalia）', '译名统一：下文均作“斯卡利亚”'),
        (10, '以下是25岁的美国高尔夫球职业联赛的老手汤姆·凯特（Tom Kite）', '以下是在美国高尔夫球职业联赛征战了25年的老将汤姆·凯特（Tom Kite）',
         '误译：a 25-year veteran of the PGA Tour 指征战25年，凯特当时已年近五十'),
        (10, 'A. A Milne', 'A. A. Milne', '注释：缩写点脱落'),
        (10, 'Ibid. [1003b].', 'Ibid. [1103b].', '注释：贝克尔页码误为1003b（《尼各马可伦理学》第二卷第一章在1103a—b）'),
        (10, '伯纳德·威廉斯 (Bernard Williams)', '伯纳德·威廉斯（Bernard Williams）', '注释：括号格式'),
        # chapter 9
        (11, '1977年，一个澳大利亚的人权委员会', '1997年，一个澳大利亚的人权委员会',
         '事实错误：关于“被偷的一代”的《带他们回家》报告发表于1997年（下文时任总理霍华德1996年起执政）'),
        (11, '任何人都能遣责不公正的行为', '任何人都能谴责不公正的行为', '错字：遣→谴'),
        (11, '对于道德自由主义者而言，自由就意味着', '对于道德个人主义者而言，自由就意味着', '术语错误：上文定义的是“道德个人主义”'),
        (11, '我所做出一个选择、一个承诺', '我所做出的一个选择、一个承诺', '漏字：的'),
        (11, '身份、登记、习俗、传统', '身份、等级、习俗、传统', '错字：登记→等级（rank）'),
        (11, '它追求某种功利或连贯性', '它追求某种统一性或连贯性', '误译：麦金泰尔说的是 unity or coherence（统一性或连贯性），不是“功利”'),
        (11, '与墨西哥的华雷斯（Juarez）是两个相邻的小镇', '与墨西哥的新拉雷多（Nuevo Laredo）是两个相邻的小镇',
         '事实错误：与拉雷多隔格兰德河相望的是新拉雷多（华雷斯城的对岸是埃尔帕索）'),
        (11, '将自己6英尺高、6英寸宽、250磅的身躯', '将自己6英尺6英寸高、250磅重的身躯', '误译：6-foot-6 指身高6英尺6英寸，不是“6英寸宽”'),
        (11, '李是北方联邦军队的士官', '李是北方联邦军队的军官', '用词错误：李当时是联邦军上校，属军官而非士官'),
        (11, '李的两难境界', '李的两难境地', '错字：境界→境地'),
        (11, '成为马萨诸塞州的参议员主席（1978～1996）', '成为马萨诸塞州参议院议长（1978～1996）', '误译：President of the Massachusetts Senate 是州参议院议长'),
        (11, '检察官不会判他哥哥死刑，可是他们还是判了。因为自己的告发，哥哥被判死刑，这让戴维备受煎熬。',
         '检察官不会对他哥哥求处死刑，可是他们还是求处了。因为自己的告发，哥哥可能被判死刑，这让戴维备受煎熬。',
         '误译/事实：检察官是“求处”死刑（sought the death penalty），泰德最终认罪换得终身监禁（下句），并未被判死刑'),
        (11, 'pp.3–29 See also', 'pp.3–29. See also', '注释：缺句点'),
        (11, 'pp.46–64 Hiroko Tabuchi', 'pp.46–64; Hiroko Tabuchi', '注释：缺分号'),
        (11, 'On RepJohn Conyers’s', 'On Rep. John Conyers’s', '注释：缩写点与空格脱落'),
        (11, 'FuseAction=Issues. Home', 'FuseAction=Issues.Home', '注释：网址中多空格'),
        (11, 'Alfred L Brophy', 'Alfred L. Brophy', '注释：缩写点脱落'),
        (11, 'Statelineorg', 'Stateline.org', '注释：网址中的点脱落'),
        (11, 'details/story? contentId', 'details/story?contentId', '注释：网址中多空格'),
        (11, 'no127 (July 29, 2008)', 'no. 127 (July 29, 2008)', '注释：缩写点脱落'),
        (11, 'ed. Perter Laslett', 'ed. Peter Laslett', '注释：人名拼错'),
        (11, 'Michael J Sandel, Democracy', 'Michael J. Sandel, Democracy', '注释：缩写点脱落'),
        (11, 'Robert H Bremner', 'Robert H. Bremner', '注释：缩写点脱落'),
        (11, 'Franklin D Roosevelt', 'Franklin D. Roosevelt', '注释：缩写点脱落'),
        (11, 'Code of the Streeet', 'Code of the Street', '注释：拼写错误'),
        (11, 'Clark, “Israel an Airlift', 'Clark, “Israel: An Airlift', '注释：标题中的冒号脱落'),
        (11, '“Israel Stormy Skies', '“Israel: Stormy Skies', '注释：标题中的冒号脱落'),
        (11, '(New York: Basic Books, 1983), p62.', '(New York: Basic Books, 1983), p.62.', '注释：缩写点脱落'),
        (11, 'Douglas A Irwin', 'Douglas A. Irwin', '注释：缩写点脱落'),
        (11, '把tituba、sarah Good和sarah Osborne指控为女巫', '把Tituba、Sarah Good和Sarah Osborne指控为女巫', '译注：人名首字母大写误转'),
        # chapter 10
        (12, '玛格丽特也直截了当地采用了它', '马歇尔也直截了当地回应了它', '误译：马歇尔是正面回应（takes it head-on）这一论证，不是“采用”它（下句即说她提供了相反的阐释）'),
        (12, '（通过辅助手段的或不通过非辅助手段）', '（通过或不通过辅助手段）', '语病：双重否定，原意“无论是否借助辅助生育”'),
        (12, '可能是结婚并维持婚姻的', '可以结婚并维持婚姻', '语病：may marry and stay married'),
        (12, '认为：同性婚姻在本性上是不稳定的', '认为：同性关系在本性上是不稳定的', '误译：原文是同性关系（same-sex relationships）'),
        (12, '在动乱中损失的那些自然奇迹', '在无序扩张中损失的那些自然奇迹', '误译：罗伯特·肯尼迪原话 the loss of our natural wonder in chaotic sprawl'),
        (12, '提议要使个人所得税降到20世纪90年代的水平时', '提议要使最高个人所得税率回到20世纪90年代的水平时',
         '事实错误：奥巴马主张把最高税率恢复到90年代较高的水平，不是“降到”'),
        (12, '称他为企图扩展财富的社会主义者', '称他为企图“均分财富”的社会主义者', '误译：spread the wealth 指平摊财富'),
        (12, '那么，那些关于收入分配的争论，就不会找到政治上的影响力；',
         '那么就可能获得那些单纯关于收入分配的争论所得不到的政治影响力；',
         '误译（意思反了）：原意是关注不平等的公民性后果，可能获得单纯的收入分配争论所得不到的政治影响力'),
        (12, 'Theodore H White', 'Theodore H. White', '注释：缩写点脱落'),
        (12, '见at www.jfk.library.org', '见 www.jfklibrary.org', '注释：多余的“at”；网址拼错（同注[388]）'),
        (12, 'Michael J Sandel, Democracy', 'Michael J. Sandel, Democracy', '注释：缩写点脱落'),
        (12, 'Kansas,”March 18', 'Kansas,” March 18', '注释：缺空格'),
        (12, 'Service,”University', 'Service,” University', '注释：缺空格'),
        (12, 'Immigrate,”The', 'Immigrate,” The', '注释：缺空格'),
        (12, 'Alfred A Knopf', 'Alfred A. Knopf', '注释：缩写点脱落'),
    ],
    'q14': [
        (5, '40074千米（地球的直径）', '40074千米（地球的周长）', '事实错误：40074千米是赤道周长（地球直径约12742千米）'),
        (6, '世界各国政府答成共识', '世界各国政府达成共识', '错字：答成→达成'),
        (6, '所以水蒸气就会冷凝成气溶胶，形成云', '所以水蒸气就会在气溶胶上冷凝，形成云',
         '误译：水汽以气溶胶为凝结核冷凝成云（上段即说“没有这些微小的颗粒，水蒸气就不能凝结成云”）'),
        (6, 'MOVE', '哈德来环流、费雷尔环流和极地环流', '如前文所述，地球的形状', '排版：小标题被错置在图6与方框1之前，移回其正文之前'),
        (7, '强烈的信风推动风暴向南拖过美国中部', '强烈的信风推动风暴向南拖过中美洲', '误译：“米奇”飓风登陆的是中美洲（洪都拉斯等，见第四章），不是美国中部'),
        (7, '强烈的西风和洋流使其保持在那里', '强烈的西向风和西向洋流使其保持在那里',
         '误译：把暖池推在西太平洋的是自东向西吹的信风；“西风”是自西吹来的风，方向正相反'),
        (7, '西风和洋流得到增强', '西向风和洋流得到增强', '误译：同上（拉尼娜时期增强的是西向的信风）'),
        (7, '大气——海洋环流模型（AOGCMs）', '大气—海洋环流模型（AOGCMs）', '标点：复合名称用连接号“—”，与下文“大气—海洋环流模型”一致'),
        (8, '75％～80%', '75%～80%', '符号：全角、半角百分号混用'),
        (9, '大约400万年后关闭的巴拿马通道', '大约400万年前关闭的巴拿马通道',
         '事实错误：巴拿马通道约400万年前关闭（上文：北大西洋深层水“可能只有400万年的历史”）'),
        (11, '冰雪不断积累，反照，即反射回空间的阳光就会增加', '冰雪不断积累，反照率，即反射回空间的阳光就会增加', '漏字：反照→反照率（同段下文即作“反照率”）'),
        (11, '劳伦泰德河和密西西比河的河道', '圣劳伦斯河和密西西比河的河道', '误译：并无“劳伦泰德河”（劳伦泰德是冰盖名），排泄其融水的是圣劳伦斯河'),
        (11, '随着海洋降低，连接相邻各大陆', '随着海平面降低，连接相邻各大陆', '漏字：海洋→海平面'),
        (12, '包括太阳光斑和火山爆发', '包括太阳黑子和火山爆发', '误译：与火山并列的自然因素是太阳黑子（太阳活动周期）'),
        (13, '每个楔子每年可封存约10亿兆吨的碳', '每个楔子每年可封存约10亿吨的碳', '量级错误（多字）：一个“楔子”为每年10亿吨碳（同章下文“另一个每年10亿吨的楔子”）'),
        (13, '生物碳酸盐', '碳酸氢盐', '误译：HCO₃⁻是碳酸氢根（bicarbonate），不是“生物碳酸盐”（两处）'),
        (13, '一场雪崩把湖水混杂在一起', '一场山崩把湖水混杂在一起', '误译：喀麦隆尼奥斯湖一带无积雪，触发湖水翻涌的是山崩（滑坡）'),
        (14, '正常的冰期——间冰期旋回', '正常的冰期—间冰期旋回', '标点：复合名称用连接号，与全书“冰期—间冰期旋回”一致'),
        (14, '南极洲——澳大利亚大陆', '南极洲—澳大利亚大陆', '标点：复合名称用连接号'),
        (15, '生物群的标本化和多样化', '生物群的物种形成和多样化', '误译：避难所理论讲的是物种形成（speciation），不是“标本化”'),
    ],
    'q15': [
        ('*', ASCII_COMMA, '，', '标点：中文里的半角逗号改为全角'),
        ('*', ASCII_COLON, '：', '标点：中文里的半角冒号改为全角'),
        (2, 'William D.Nordhaus', 'William D. Nordhaus', '版权页：缺空格'),
        (2, 'All right reserved.', 'All rights reserved.', '版权页：rights 漏 s'),
        (3, '最高荣誉讲席—斯特林经济学讲席教授', '最高荣誉讲席——斯特林经济学讲席教授', '标点：破折号（与译者序一致）'),
        (3, re.compile(r'(?<=\d) (?=[年位])'), '', '排版：数字与汉字间多余空格'),
        (3, '· ', '·', '排版：间隔号后多余空格'),
        (4, 'EMBA 课程', 'EMBA课程', '排版：多余空格'),
        (6, '让人心惊胆颤', '让人心惊胆战', '错字：心惊胆战'),
        (6, '内生经济理论的创立者保罗·罗默', '内生增长理论的创立者保罗·罗默', '术语：罗默创立的是内生增长理论（下文即“内生经济增长模型”）'),
        (6, '资料详实', '资料翔实', '用词：翔实'),
        (6, 'HREF', '这本书的题目是“气候赌场”', '（见此处）', 'part0012#climcasino', '链接：“见此处”原指向自身，改指第1章原文'),
        (12, 'ANCHOR', '简单的回答是，全球变暖是对人类与自然界的一个主要威胁', 'part0012#climcasino', '链接：为上一条加目标锚点'),
        ('*', re.compile(r', ” ?(?=\S)'), ',” ', '注释：英文篇名后的逗号、后引号与空格错位（, ”X → ,” X）'),
        (14, '气候变化经济学家是坦率的', '气候变化经济学是直截了当的', '误译：同第1章“气候变化经济学是直截了当的”（The economics of climate change is straightforward）'),
        (14, '不受管制的市场也起了很大作用，因为', '不受管制的市场会产生过多的排放，因为', '误译：原意是不受管制的市场产生过多（第1章：“不受管制的市场产生了太多的CO2”）'),
        (14, '（3.4%—1.8%）', '（3.4%－1.8%）', '符号：减号误为破折号'),
        (14, '通过布设成千上万的电脑代码线路', '通过编写成千上万行电脑代码', '误译：lines of code 是代码行'),
        (14, '就意味着一个世纪增加3.3倍', '就意味着一个世纪增长到原来的3.3倍', '表述：1.012的100次方≈3.3，是“增长到3.3倍”'),
        (14, '比2000年高1.6倍到5.4倍', '是2000年的1.6倍到5.4倍', '表述：倍数关系'),
        (14, '针对这些巨大的不确定作出反应', '针对这些巨大的不确定性作出反应', '漏字：不确定性'),
        (14, '（1—a）S=4εσT 4', '（1－a）S=4εσT⁴', '公式：减号误为破折号；T的4次方上标丢失'),
        (14, 'climate/pdf/Gcm. pdf', 'climate/pdf/Gcm.pdf', '注释：网址中多空格'),
        (14, 'www.aip. org/history', 'www.aip.org/history', '注释：网址中多空格'),
        (14, '（CO2 /GDP）', '（CO2/GDP）', '排版：多余空格'),
        (15, '表面的温度将是—19\u2009℃', '表面的温度将是－19\u2009℃', '符号：负号误为破折号'),
        (15, '即与表9中表示的3', '即与图9中表示的3', '错字：此处引用的是图9（本章无表9）'),
        (15, 'Karl E Taylor', 'Karl E. Taylor', '注释：人名缩写漏点'),
        (15, 'Jeff Tollison', 'Jeff Tollefson', '注释：人名拼写（Nature 记者 Jeff Tollefson）'),
        (15, 'eds.,Managing', 'eds., Managing', '注释：缺空格'),
        (16, '低纬度地区温度增加，因此，高于现在冰盖的小冰盖的顶部也变暖', '海拔越低温度越高，因此，比现在冰盖低的小冰盖的顶部也更暖', '误译：说的是海拔（elevation）反馈，缩小的冰盖顶部更低因而更暖'),
        (16, '如果全球温度变暖1度，', '如果全球温度变暖1\u2009℃，', '体例：温度单位与同段一致'),
        (16, '因为它只涉及人们无法充分理解的动态和非线性反应', '因为它涉及人们尚未充分理解的动态和非线性反应', '误译：only imperfectly understood'),
        (16, '这可以用持续的GIS和海平面上升的分析来证明', '这可以继续用GIS和海平面上升的分析来说明', '表述：continuing the analysis'),
        (16, '虽然在20世纪之前不久没有可靠的仪表温度记录', '虽然可靠的仪器温度记录只能追溯到20世纪之前不久', '表述：语序错乱'),
        (16, '在过去5000年间', '在过去5 000年间', '体例：同段作“5 000年”'),
        (16, '而且，所有这一切都要取决于货币、', '而且，所有这一切都要受制于金钱、', '误译：money（政治中的金钱）'),
        (16, '他们大多数人正常预期的是并未发生的崩溃', '他们大多数人经常预言的是并未发生的崩溃', '误译：regularly'),
        (16, 'Climate System，” Nature 105, no.6（2008）', 'Climate System，” Proceedings of the National Academy of Sciences 105, no.6（2008）', '注释：Lenton 等文载 PNAS 第105卷第6期，非 Nature'),
        (16, '如果你抓住一根枝条并捆住它，然后放开，最后的阶段是什么将取决于你是不是把它捆到折断的一点', '如果你抓住一根枝条把它弯曲，然后放开，最后的状态将取决于你是不是把它弯到了折断的程度', '误译：bend（弯曲），不是“捆”'),
        (19, '是受控与未受控经济之间的区别', '是受控与未受控生态系统之间的区别', '误译：下句即定义“生态系统”（managed vs unmanaged ecosystems）'),
        (19, '液体培养法', '水培法', '术语：hydroponics 通译水培'),
        (19, '液体培养设施', '水培设施', '术语：hydroponics 通译水培'),
        (19, '至少在两个世纪前，疾病与死亡', '直到两个世纪前，疾病与死亡', '误译：as recently as'),
        (19, '某些地区有自然的焦点政策', '某些领域有自然的焦点政策', '误译：areas 指领域'),
        (19, '消除艾滋病、天花，金融崩溃，或者核战争', '消除艾滋病、天花、金融崩溃或者核战争', '标点：并列用顿号'),
        (19, 'Impacts,Adaptation', 'Impacts, Adaptation', '注释：缺空格'),
        (20, '(“人均消费”代表食物、住房、教育和其他项目的平均消费。)', '（“人均消费”代表食物、住房、教育和其他项目的平均消费。）', '标点：中文用全角括号'),
        (20, '改变耕作方法和耕种时间这类适应性措施', '改变作物品种和播种时间这类适应性措施', '误译：IPCC 原文 altered cultivars and planting times'),
        (20, '全球天气形式的重大变化', '全球天气形态的重大变化', '用词：weather patterns'),
        (20, '相对于不超过3\u2005℃的不变暖基线，变暖会降低全球食物价格', '相对于不变暖的基线，不超过3\u2005℃的变暖会降低全球食物价格', '误译：限定语错置'),
        (20, '感觉是直接的。', '其中的道理很直观。', '误译：The intuition is straightforward'),
        (20, '5（=0.25×20） %', '5（=0.25×20）%', '排版：多余空格'),
        (20, '在下半个世纪左右农业所受的影响将很小', '在未来半个世纪左右农业所受的影响将很小', '误译：over the next half-century'),
        (20, '在气候赌场上的欠者赔率将', '气候赌场上的赔率将', '多字/误译：odds'),
        (20, '最有利的证据是，', '最有力的证据是，', '错字：有力'),
        (20, '并不专属于RICEDICE模型', '并不专属于RICE-DICE模型', '排版：模型名漏连字符'),
        (20, '（根据美国的MESSAGE模型）', '（MESSAGE模型中的美国）', '误译：MESSAGE 是 IIASA 的模型，此处说的是该模型中的美国这一地区'),
        (20, '（2×2×2×2×2×2)=64倍', '（2×2×2×2×2×2）=64倍', '标点：括号不配对'),
        (20, 'NIPA Table1.3.5', 'NIPA Table 1.3.5', '注释：缺空格'),
        (20, '价格弹性是–1', '价格弹性是－1', '符号：负号'),
        (21, '如果一个年轻的坦桑尼亚姑娘感染了疟疾', '如果一个年轻的坦桑尼亚姑娘死于疟疾', '误译：与上句“死去”并列，计入 DALY 的是死亡'),
        (21, '33个DALYS', '33个DALYs', '体例：DALYs'),
        (21, '根据WHO研究团体的估算', '根据WHO研究团队的估算', '用词：与全章“团队”一致'),
        (21, '指向了驱动空调引起的电力需求和CO2排放增长', '指出了空调驱动的电力需求和CO2排放增长', '误译：语序'),
        (21, '更为普遍的层面，WHO', '在更为普遍的层面上，WHO', '漏字：介词结构不完整'),
        (21, 'Alan D.Lopez', 'Alan D. Lopez', '注释：缺空格'),
        (21, re.compile(r'(?<=[a-z])\.(?=上找到)'), '', '注释：网址后多余句点'),
        (21, '（Washington, DC: World Bank, 2006），Chapter 14.', '（Washington, DC: World Bank, 2006）, Chapter 14.', '注释：英文著录中误用全角逗号'),
        (22, '以至于甚至郊狼对越境也犹豫不定', '以至于甚至“郊狼”（coyote，指偷运越境者的蛇头）对越境也犹豫不定', '误译：coyote 在美墨边境指蛇头，直译“郊狼”令人费解，补注'),
        (22, '随着海洋变暖，它们将扩大', '随着海洋变暖，它们将膨胀', '用词：热膨胀'),
        (22, '第二个模型贯穿了关于全球温度增加将限于在1900年水平上增加2\u2005℃的假设', '第二个情景假设全球温度增加被限制在比1900年水平高2\u2005℃以内', '误译：此处是情景而非模型；语句不通'),
        (22, '我将在第11章中回头处理棘手的估值问题，在这一章讨论了物种保护', '我将在第11章中回头处理棘手的估值问题，那一章将讨论物种保护', '误译：时态与指代'),
        (22, '如荷兰和曼哈顿岛，这是一种适用的方法', '如荷兰和曼哈顿岛，这是一种适用的方法。', '漏字：段末缺句号'),
        (22, '它谨慎，而不是失败主义者', '它是审慎的，而不是失败主义的', '误译：形容策略而非人'),
        (22, '相关度是—0.09', '相关度是－0.09', '符号：负号'),
        (22, '大气中的CO2与海水结合形成碳酸（H2CO2）', '大气中的CO2与海水结合形成碳酸（H2CO3）', '化学式：碳酸是H2CO3'),
        (22, '这种化合物会释放出正氧离子进入水中', '这种化合物会释放出氢离子进入水中', '科学性错误：碳酸电离释放的是氢离子（H⁺），降低pH'),
        (23, '因为基本原因（不同于更暖的水对飓风的影响）', '因为基本物理原理（不同于更暖的水对飓风的影响）', '误译：basic physics'),
        (23, '那么在下半个世纪，保证国家的资本', '那么在未来半个世纪，保证国家的资本', '误译：over the next half-century'),
        (23, '483—485； and Thomas', '483—485; and Thomas', '注释：英文著录中误用全角分号'),
        (23, 'Nature,  Climate Change', 'Nature Climate Change', '注释：期刊名为 Nature Climate Change'),
        (23, 'Barbara M.Fraumeni', 'Barbara M. Fraumeni', '注释：缺空格'),
        (24, '然后，它们在经济上远离市场', '其次，它们在经济上远离市场', '用词：与“首先”呼应'),
        (24, '冰山作用', '冰川作用', '错字：glaciation 是冰川作用'),
        (24, '大多人同意', '大多数人同意', '漏字'),
        (24, '南非的弗洛勒尔角', '南非的开普植物区', '误译：Cape Floral Region（开普植物区），不是地名“弗洛勒尔角”'),
        (24, '试验室', '实验室', '用词：实验室'),
        (24, '警示一只船', '警示一艘船', '量词'),
        (24, '物种和生态系统在生物学上与灯塔有相似性', '物种和生态系统在经济学上与灯塔有相似性', '误译：此处类比的是经济属性（正外部性）'),
        (24, '很有可能，某些创造力从所有这些潜在丧失中造就的总价值将大于家庭收入', '很有可能，只要发挥一点创造力，从所有这些潜在丧失中得出的总价值就会大于家庭收入', '误译：with some creativity'),
        (24, '罗伯特·梅（Robere May）', '罗伯特·梅（Robert May）', '错字：Robert'),
        (24, '大于3000种蚊子物种之一的丧失', '大于3 000种蚊子物种之一的丧失', '体例：数字分节'),
        (24, '例如，(e)定量分析', '例如，（e）定量分析', '标点：与上文（a）—（e）一致'),
        (24, '“易危”有一些类似的标准，用第五个就是', '“易危”有一些类似的标准，第五个就是', '多字'),
        (24, 'No Number?” Economic Perspectives 26', 'No Number?” Journal of Economic Perspectives 26', '注释：刊名为 Journal of Economic Perspectives'),
        (24, 'Journal of Environmental and Economics Management', 'Journal of Environmental Economics and Management', '注释：刊名词序'),
        (24, '1955） .', '1955）.', '排版：多余空格'),
        (25, '● 我们看到了，高收入国家', '●\u3000我们看到了，高收入国家', '排版：项目符号后空格与其他各条一致'),
        (25, '利用对我们背后的单个部门的这些观察，让我们着眼于全局', '有了以上对单个部门的观察，让我们着眼于全局', '误译：with these observations behind us'),
        (25, '一个红袋子里的球引起了排放的迅速增加', '球落入红格则引起排放的迅速增加', '误译：轮盘赌的 pocket 是“格”，不是“袋子”'),
        (25, '一个黑袋子里的球引起了排放的缓慢增加', '球落入黑格引起排放的缓慢增加', '误译：轮盘赌的 pocket 是“格”'),
        (25, '而一个红袋子里的球可能给现在的世界谷物带', '而球落入红格则可能给现在的世界谷物带', '误译：轮盘赌的 pocket 是“格”'),
        (25, '也许红袋的数量之多', '也许红格的数量之多', '误译：轮盘赌的 pocket 是“格”'),
        (25, '连续三个红袋加上双零', '连续三个红格加上双零', '误译：轮盘赌的 pocket 是“格”'),
        (25, '在这方面它们类似于关于国防的存在主义争论', '在这方面它们类似于关于国防这类生死存亡问题的争论', '误译：existential 指关乎存亡，非“存在主义”'),
        (25, '相对于下半个世纪和一个世纪经济活动', '相对于未来半个世纪和一个世纪经济活动', '误译：over the next half-century'),
        (25, '人类社会可以免于灾难性损失适应它们', '人类社会可以适应它们而免于灾难性损失', '语序'),
        (25, 'data.worldbank.org/datacatalog/', 'data.worldbank.org/data-catalog/', '注释：网址漏连字符（同第7章注）'),
        (27, '— Wilson Mizner', '—Wilson Mizner', '排版：与其他题记一致'),
        (28, '但它们在基本的“成本—收益”的模式中更趋复杂', '但这些只是在基本的“成本—收益”模式上增加了复杂性', '误译：complications on the basic pattern'),
        (28, '把海水抽低1 000英尺', '把海水抽高1 000英尺', '误译：把海水抽到南极冰盖上是向上抽'),
        (28, '每年8×1017加仑水', '每年8×10¹⁷加仑水', '公式：指数上标丢失（正文作“80亿亿加仑”）'),
        (28, '每年5×1013 kWh', '每年5×10¹³ kWh', '公式：指数上标丢失'),
        (28, 'Ricke, M. Granger, and Myles R.Allen', 'Ricke, M. Granger Morgan, and Myles R. Allen', '注释：作者名 M. Granger Morgan 漏姓；缺空格'),
        (28, 'Can We Survive Technology，”Fortune', 'Can We Survive Technology?” Fortune', '注释：篇名原有问号'),
        (28, '地球科学涉及的不仅仅是气候科学或设计巧妙的太空镜', '地球工程涉及的不仅仅是气候科学或设计巧妙的太空镜', '错字：本注讲地球工程'),
        (28, '163.Parson. Keith.DeadlockOnGovernance', '163.Parson.Keith.DeadlockOnGovernance', '注释：网址中多空格'),
        (29, 'SHIFT', 7, 1),
        (29, 'SPLIT', '(6)', '[2]', '(7)', 'part0029#claude_m7', 'part0029#claude_n7'),
        (29, 'RELINK', '天然气是最清洁的化石燃料', '[2]', '(7)', 'part0029#claude_n7', 'part0029#claude_m7'),
        (29, '天然气是最清洁的化石燃料，发电时每千瓦时', '天然气是最清洁的化石燃料，发电时每千瓦时', '注释：电子书把注释（7）（EIA 发电成本）误并入注释（6），正文注码作无链接的“[2]”；拆分为独立注释并重新编号，其后各注顺延'),
        (29, '能源+ CO2', '能源+CO2', '排版：多余空格'),
        (29, '在下半个世纪，这种突破的可能性', '在未来半个世纪，这种突破的可能性', '误译：over the next half-century'),
        (29, '因此在某种程度上，全球变暖政策大体是在气候赌场中，应对不确定但极危险的后果的主要保险，潜在革命性突破带来的有利结果，并不能', '因此，既然全球变暖政策大体是在气候赌场中应对不确定但极危险的后果的主要保险，潜在革命性突破带来的有利结果就并不能', '误译：to the extent that（既然／就……而言）'),
        (29, '其对下半个世纪生活水平的影响', '其对未来半个世纪生活水平的影响', '误译：over the next half-century'),
        (29, '数据来Carbon Dioxide', '数据来自Carbon Dioxide', '漏字'),
        (29, 'September 20，2010', 'September 20, 2010', '注释：英文著录中误用全角逗号'),
        (29, 'www.epa.gov/cleanenergy-and-you/', 'www.epa.gov/cleanenergy/energy-and-you/', '注释：网址漏“/energy”'),
        (29, '%20 Golomb', '%20Golomb', '注释：网址中多空格'),
        (29, 'Lachner树', 'Lackner树', '错字：Lackner（正文作“拉克内”）'),
        (29, '参看Ray Kurzweil: The Singularity', '参看Ray Kurzweil, The Singularity', '注释：作者与书名之间应为逗号'),
        (30, '每1000千瓦时半吨CO2', '每1 000千瓦时半吨CO2', '体例：数字分节'),
        (30, '总的成本降低曲线', '总的减排成本曲线', '误译：aggregate abatement-cost curve'),
        (30, '说明了降低CO2成本的方法', '说明了估算CO2减排成本的方法', '误译：abatement cost 是减排成本'),
        (30, '一直在研究降低CO2减排成本的问题', '一直在研究CO2减排成本的问题', '误译：abatement cost 是减排成本'),
        (30, '这第二种情况仍然带有理想色彩。因为它假设', '这第二种情况仍然带有理想色彩，因为它假设', '标点：句号误断'),
        (30, '鉴于对其他模型编制的结果有兴趣的人', '对于那些对其他模型编制的结果有兴趣的人', '语病'),
        (30, 'V=1 000—50/（1.05）—50/（1.05）2—……—50/（1.05）9= 595美元', 'V=1 000－50－50/（1.05）－50/（1.05）²－……－50/（1.05）⁹=595美元', '公式：减号误为破折号，指数上标丢失；且漏了第一年的“－50”（按原式只得645美元，补上后正得595美元）'),
        (30, 'et al.,“Simultaneously', 'et al., “Simultaneously', '注释：缺空格'),
        (31, '实际利率就是每年6%—2%=4%', '实际利率就是每年6%－2%=4%', '符号：减号误为破折号'),
        (31, '1美元/1.04= 0.96美元', '1美元/1.04=0.96美元', '排版：多余空格'),
        (31, '这就意味着，我们应该相对于今天的消费来贴现未来消费的价值。因为我们认为', '这就意味着，我们应该相对于今天的消费来贴现未来消费的价值，因为我们认为', '标点：句号误断'),
        (31, '（1+r）–50，这里r是贴现率', '（1+r）⁻⁵⁰，这里r是贴现率', '公式：指数上标丢失'),
        (31, '（1.04）–50=0.141', '（1.04）⁻⁵⁰=0.141', '公式：指数上标丢失'),
        (31, '在政府的贴现率为7%时，1亿美元的投资通不过成本—收益检验', '在政府的贴现率为7%时，这项1 000万美元的投资通不过成本—收益检验', '误译：投资是1 000万美元，1亿美元是收益（见括号内算式）'),
        (31, '对下一代是（1/2）2=1/4', '对下一代是（1/2）²=1/4', '公式：指数上标丢失'),
        (31, '1+1/2+（1/2）2 +（1/2）3+……=2', '1+1/2+（1/2）²+（1/2）³+……=2', '公式：指数上标丢失'),
        (31, '在家庭医疗体系、热带病的治疗', '在国内医疗体系、热带病的治疗', '误译：domestic health care（国内医疗体系）'),
        (31, 'Kenneth J.Arrow', 'Kenneth J. Arrow', '注释：缺空格'),
        (31, 'J. Bruce, H.Lee, and E. Haites', 'J. Bruce, H. Lee, and E. Haites', '注释：缺空格'),
        (31, 'The Economics of Global Warming(Washington, DC: Institute of International Economics, 1992)', 'The Economics of Global Warming（Washington, DC: Institute for International Economics, 1992）', '注释：括号体例；机构名为 Institute for International Economics'),
        (31, '《斯特恩报告》: Nicholas Stern', '《斯特恩报告》：Nicholas Stern', '标点：中文冒号'),
        (34, '是否最好的目标，将取决于实现它的成本', '哪个目标最好，将取决于实现它的成本', '语病'),
        (34, '是1994年通过的《联合国气候变化框架公约》', '是1994年生效的《联合国气候变化框架公约》', '史实：公约1992年通过，1994年生效'),
        (34, 'pressReleasesAction.do？reference=MEMO/07/16； G8', 'pressReleasesAction.do?reference=MEMO/07/16; G8', '注释：网址中误用全角问号；英文著录中误用全角分号'),
        (34, 'J. R. Petitetal.', 'J. R. Petit et al.', '注释：缺空格'),
        (34, 'Past 420, 000 Years', 'Past 420,000 Years', '注释：数字中多空格'),
        (34, 'vostok/vostok. 1999. temp.dat', 'vostok/vostok.1999.temp.dat', '注释：网址中多空格'),
        (35, '比如学费与研究生薪金前景', '比如学费与毕业后的薪金前景', '误译：graduate salary prospects 指毕业生的薪金前景'),
        (35, '每年的成本除以全球总收益的比率', '每年的成本除以全球总收入的比率', '错字：收入'),
        (35, '成悖论的是，', '矛盾的是，', '语病'),
        (35, '这种形状来自第17章中评述的经济损失研究', '这种形状来自第12章中评述的经济损失研究', '错误：损失研究的评述在第12章（图22），第17章是气候政策史'),
        (35, '也许季风形式的某种不稳定性', '也许季风形态的某种不稳定性', '用词：monsoon patterns'),
        (35, '我在DICE-2010年模型中增加了2015年的排放波动', '我在DICE-2010年模型中增加了2015年的排放脉冲', '术语：emissions pulse'),
        (35, 'D/Y=0.006（T/3.5）20，', 'D/Y=0.006（T/3.5）²⁰，', '公式：指数上标丢失'),
        (35, '指数20指向在3℃时一次急剧的中断', '指数20指向在3.5℃时一次急剧的中断', '错误：按该函数，3℃时损失仅约收入的0.03%，急剧中断在3.5℃'),
        (35, '里约热内卢，1992年7月3—14日', '里约热内卢，1992年6月3—14日', '史实：里约环发大会于1992年6月3—14日举行'),
        (35, 'aconf15126-lannexl.htm', 'aconf15126-1annex1.htm', '注释：网址中数字1误为字母l'),
        (36, '120522_CO2_Forecast_PPT_SPSG. pdf', '120522_CO2_Forecast_PPT_SPSG.pdf', '注释：网址中多空格'),
        (36, '对辐射强迫的基本描述，参看第50页注［2］', '对辐射强迫的基本描述，参看第4章注释(6)', '互见：原指纸书页码，本书无对应页码，改指第4章注释(6)'),
        (36, 'BEA, 假设个人消费为GDP的67%, 1.25亿个家庭，并假设', 'BEA，假设个人消费为GDP的67%，1.25亿个家庭，并假设', '标点：中文里的半角逗号'),
        (36, 'Jhih-Shyang Shih: “Impact', 'Jhih-Shyang Shih, “Impact', '注释：著录标点'),
        (37, '注意：纵轴单位是吨，而不是美吨（2205磅对2000磅）', '注意：纵轴单位是公吨，而不是美吨（2 205磅对2 000磅）', '用词：metric ton；数字分节'),
        (37, '一个大型电厂可能每年烧5亿吨煤', '一个大型电厂可能每年烧500万吨煤', '数字错误：按25美元/吨CO2、年纳税近4亿美元推算，应为500万吨（5亿吨约为美国全年用煤量的一半）'),
        (37, '煤、油料和石油是CO2的主要来源', '煤、石油和天然气是CO2的主要来源', '误译：coal, oil, and natural gas'),
        (37, '一种制度会给碳贷款，当树被砍伐并烧掉时', '一种制度会给予碳信用，当树被砍伐并烧掉时', '误译：credit（记入信用）与下文 debit（欠债）相对'),
        (37, '比较，见:William Nordhaus', '比较，见William Nordhaus', '标点：多余冒号'),
        (37, '研究中找到:A U.S.Cap-and-Trade', '研究中找到：A U.S. Cap-and-Trade', '标点：中文冒号；缺空格'),
        (37, 'Climate_Change.pdf； Metcalf', 'Climate_Change.pdf; Metcalf', '注释：英文著录中误用全角分号'),
        (38, '斯科特·巴伦特（Scott Barrent）', '斯科特·巴雷特（Scott Barrett）', '错字：Scott Barrett（注释中即作 Barrett）'),
        (38, '1994年通过的《联合国气候变化框架公约》', '1994年生效的《联合国气候变化框架公约》', '史实：公约1992年通过，1994年生效'),
        (38, '实际上美国住宅在交通运输或发电中使用的能源全都没有进入国际贸易', '实际上美国住宅、交通运输或发电中使用的能源全都没有进入国际贸易', '误译：三者并列'),
        (38, '有趣研究是:Inge Kaul', '有趣研究是Inge Kaul', '标点：多余冒号'),
        (38, 'http://unfccc. int/2860.php', 'http://unfccc.int/2860.php', '注释：网址中多空格'),
        (38, 'http://phe.rockefeller. edu/verification/', 'http://phe.rockefeller.edu/verification/', '注释：网址中多空格'),
        (38, 'Barrett, Environmet and Statecraft', 'Barrett, Environment and Statecraft', '注释：书名拼写'),
        (39, '一个具体的例子是政府对器械的管制', '一个具体的例子是政府对电器的管制', '误译：appliance（电器）'),
        (39, '在其使用寿命中的资金和燃料成本大于500美元', '在其使用寿命中的资金和燃料成本要多出500美元', '误译：多出500美元，与下文每吨50美元相合'),
        (39, '这个常规由我将在本章后半部分讨论的我所谓的“能源成本短视”证实了', '这一反常现象可以用我将在本章后半部分讨论的、我所谓的“能源成本短视”来解释', '误译：anomaly（反常现象），且语序不通'),
        (39, '“未来资源”（RfF）', '“未来资源”（RFF）', '体例：RFF'),
        (39, '同时，它多计算了成本，到了消费者做出不良决策的程度', '同时，在消费者做出不良决策的情况下，它又多计算了成本', '误译：to the extent that'),
        (39, '可以取代燃煤电站。她得到了', '可以取代燃煤电站。它得到了', '代词：指国家用“它”'),
        (39, '我的行为有一长条的理由', '我的行为有一长串的理由', '用词'),
        (39, '在这种环境下，总量管制性排放限制将确保', '在这种环境下，管制性排放限制将确保', '误译：此处讲管制（regulatory limits）对碳价格的补充，不是总量管制'),
        (39, 'www.whitehouse.gov/state-of union-2013', 'www.whitehouse.gov/state-of-the-union-2013', '注释：网址漏字'),
        (39, 'Lint Barrag的研究', 'Lint Barrage的研究', '注释：人名漏字母'),
        (39, 'static-files/rulemarking/pdf', 'static-files/rulemaking/pdf', '注释：网址拼写'),
        (39, '该管制分析有1178页', '该管制分析有1 178页', '体例：数字分节'),
        (39, 'www.energypolicyoptions.org., AppendixB.', 'www.energypolicyoptions.org, Appendix B.', '注释：多余句点；缺空格'),
        (39, 'Energy Efficiency Gap？”Journal', 'Energy Efficiency Gap?” Journal', '注释：英文篇名用半角问号；缺空格'),
        (40, '什么将为我们的汽车提供燃料，来为我们的学校供暖呢', '什么将为我们的汽车提供燃料、为我们的学校供暖呢', '语病'),
        (40, '这个图显示的是CO2/GDP的比率，即脱碳率的变化率', '这个图显示的是CO2/GDP比率的变化率，即脱碳率', '误译：脱碳率就是CO2/GDP比率的变化率'),
        (40, '国际应用系统分析研究所（IIASA）的内博伊沙', '国际应用系统分析研究所（IIASA）和维也纳工业大学的内博伊沙', '误译：纳基斯诺维奇同时任职于两机构，维也纳工业大学不是另一位研究者'),
        (40, '和维也纳工业大学等研究者', '等研究者', '误译：见上条'),
        (40, '（EdmondBecquerel）', '（Edmond Becquerel）', '排版：缺空格'),
        (40, '来自几个大型论证项目的数据', '来自几个大型示范项目的数据', '误译：demonstration projects（示范项目）'),
        (40, '（JohnWeyant）', '（John Weyant）', '排版：缺空格'),
        (40, '“10, 000 Feet through', '“10,000 Feet through', '注释：数字中多空格'),
        (40, 'Valley of Death，’ ”', 'Valley of Death,’ ”', '注释：英文篇名中误用全角逗号'),
        (40, 'ARPA-E%20FY%20 2010%20Annual', 'ARPA-E%20FY%202010%20Annual', '注释：网址中多空格'),
        (42, '— Benjamin Disraeli', '—Benjamin Disraeli', '排版：与其他题记一致'),
        (43, '我在第20章中审视了这个问题，回头看看图8显示的结果会很有用', '我在第12章中审视了这个问题，回头看看图22显示的结果会很有用', '互见错误：损失研究的综述在第12章图22（图8是温度史，第20章是国家政策）'),
        (43, '球有可能落在有利的黑袋子中，或不利的红袋子中，或者可能落在危险的零或双零的袋子中', '球有可能落在有利的黑格中，或不利的红格中，或者可能落在危险的零或双零格中', '误译：轮盘赌的 pocket 是“格”'),
        (43, '大多数球会落在有利的黑袋子中', '大多数球会落在有利的黑格中', '误译：轮盘赌的 pocket 是“格”'),
        (43, '2012）； James M. Taylor', '2012）; James M. Taylor', '注释：英文著录中误用全角分号'),
        (43, '）； James Inhofe', '）; James Inhofe', '注释：英文著录中误用全角分号'),
        (43, 'policy-documents/capand-trade-taxing', 'policy-documents/cap-and-trade-taxing', '注释：网址漏连字符'),
        (43, 'Andrey Illarionov:http', 'Andrey Illarionov: http', '注释：缺空格'),
        (43, 'record_id=12589 #toc.如果', 'record_id=12589#toc。如果', '注释：网址中多空格；句号'),
        (43, 'www.nap.edu/, 你肯定', 'www.nap.edu/，你肯定', '标点：中文里的半角逗号'),
        (43, 'climatechange skeptic.blogspot', 'climatechangeskeptic.blogspot', '注释：网址中多空格'),
        (43, 'article/series /skeptics/', 'article/series/skeptics/', '注释：网址中多空格'),
        (43, '之后则为（年份—1980）', '之后则为（年份－1980）', '符号：减号误为破折号'),
        (43, 'B. D. Santer, C.Mears', 'B. D. Santer, C. Mears', '注释：缺空格'),
        (44, '人们对一些概念很熟悉，例如地心说', '人们对一些概念很熟悉，例如日心说', '错误：调查问的是地球绕太阳转（图41说明亦作“日心说”）'),
        (44, '认为《圣经》是上帝的文字', '认为《圣经》是上帝的话语', '误译：the actual word of God'),
        (44, '89%公开承认的自由派民主党人', '89%自认为是自由派的民主党人', '误译：self-identified'),
        (44, '然而有些东西从历史中消失了', '然而这个解释中还缺了些东西', '误译：something is missing from the story'),
        (44, '贝拉克·奥巴马总统签署了强有力的总量管制与交易法案', '贝拉克·奥巴马总统支持了强有力的总量管制与交易法案', '史实：该法案只在众议院通过，未成为法律，总统无从签署（见第22章）'),
        (44, '乔治·舒尔茨（George Schultz', '乔治·舒尔茨（George Shultz', '注释：人名拼写 Shultz'),
        (44, 'Science and Engineering Indicators,2012, Appendix Table 7—9, www.nsf.gov/statistics /seind12/', 'Science and Engineering Indicators, 2012, Appendix Table 7-9, www.nsf.gov/statistics/seind12/', '注释：缺空格；表号用连字符；网址中多空格'),
        (44, 'Miller, “Civic Science Literacy.”', 'Miller, “Civic Scientific Literacy.”', '注释：篇名与上注一致'),
        (44, '1992年是56%, 2001年是60%, 2010年是59%', '1992年是56%，2001年是60%，2010年是59%', '标点：中文里的半角逗号'),
        (44, '55—61； and Darren', '55—61; and Darren', '注释：英文著录中误用全角分号'),
        (44, 'concerns-global-warmingstable-lower-levels', 'concerns-global-warming-stable-lower-levels', '注释：网址漏连字符'),
        (44, 'Dunlap%20%20McCright%20 2008%20A', 'Dunlap%20%20McCright%202008%20A', '注释：网址中多空格'),
        (44, '感谢Shaun M.Tanger', '感谢Shaun M. Tanger', '注释：缺空格'),
        (45, '除非采取强制性手段，否则地球将继续变暖', '除非采取强有力的措施，否则地球将继续变暖', '误译：forceful measures（与本章末段一致）'),
        (45, '而将别国政策视为必然的战略', '而将别国政策视为既定', '误译：taking others’ policies as given'),
        (45, '（timedistant）', '（time-distant）', '排版：漏连字符'),
        (45, '每年减少4000个工作岗位', '每年减少4 000个工作岗位', '体例：数字分节'),
        (45, '这场运动最不正当的一部分是那些支持该行业主张的研究者的签名', '这场运动最不正当的一部分是拉拢那些支持该行业主张的研究者', '误译：signing up researchers（拉拢研究者）'),
        (45, '部分是为了劝戒吸烟', '部分是为了劝诫吸烟', '用词：劝诫'),
        (45, 'National Academy of Sciences(US) 107', 'National Academy of Sciences (US) 107', '注释：缺空格'),
        (45, 'Energy Information Anency', 'Energy Information Agency', '注释：拼写'),
        (45, '1996）； and Robert Proctor', '1996）; and Robert Proctor', '注释：英文著录中误用全角分号'),
        (45, '2005/05/some-it-hot.组织名单', '2005/05/some-it-hot。组织名单', '标点：句号'),
        (36, 'RFF DP 06-37, 2008年11月', 'RFF DP 08-37, 2008年11月', '注释：论文编号为 DP 08-37（见第26章注释）'),
        # —— 以下为全书英文文献著录的统一（置于列表末尾，前面的字面勘误不受影响）
        ('*', re.compile(r'(?<=[A-Za-z0-9?!.)）])，”\s?(?=[A-Za-z0-9])'), ',” ', '注释：英文篇名后误用全角逗号（，” → ,”）'),
        ('*', re.compile(r'(?<=[A-Za-z0-9.])，\s?(?=[A-Za-z])(?!NEW）)'), ', ', '注释：英文著录中误用全角逗号'),
        ('*', re.compile(r'(?<=[A-Za-z0-9.]) （'), '（', '排版：全角括号前多余空格'),
        ('*', re.compile(r'(?<=[A-Za-z0-9]):(?=[A-Z])'), ': ', '注释：英文冒号后缺空格'),
        ('*', re.compile(r'(?<=\d）)：\s?(?=\d)'), ': ', '注释：页码前误用全角冒号'),
        ('*', re.compile(r'(?<=[A-Za-z）])：\s?(?=[A-Z])(?!ENSO转)'), ': ', '注释：英文著录中误用全角冒号'),
        ('*', re.compile(r'(?<=\d）):(?=\d)'), ': ', '注释：页码前冒号后缺空格'),
        ('*', 'Mitigation,Adaptation', 'Mitigation, Adaptation', '注释：缺空格'),
        ('*', '1, 000 Feet', '1,000 Feet', '注释：数字中多空格'),
        ('*', re.compile(r'W/m2(?!\d)'), 'W/m²', '单位：平方米的上标丢失'),
        ('*', '详实', '翔实', '用词：翔实'),
        ('*', 'GHGS', 'GHGs', '体例：GHGs'),
        ('*', re.compile(r'(?<=[\w.)]), ?(?=可获取于|可获得于)'), '，', '标点：中文里的半角逗号'),
        ('*', re.compile(r'(?<=[\u4e00-\u9fff]):(?=[A-Za-z])'), '：', '标点：中文后用全角冒号'),
        ('*', 'Conventionon Climate', 'Convention on Climate', '注释：缺空格'),
        ('*', 'Forumon Energy', 'Forum on Energy', '注释：缺空格'),
        ('*', re.compile(r'(?<=[\u4e00-\u9fff，。、])[ \u2005\u2006\u2009]+(?=[\u4e00-\u9fff。，、])'), '', '排版：汉字之间多余空格'),
        ('*', re.compile(r'(?<=[a-z])\.(?=上(?:免费)?(?:找到|获得))'), '', '注释：网址后多余句点'),
        ('*', 'http：//', 'http://', '注释：网址中误用全角冒号'),
        ('*', re.compile(r'） \.(?!\d)'), '）.', '排版：句点前多余空格'),
        ('*', re.compile(r'(?<=[A-Za-z.])，\s?“\s?(?=[A-Z])'), ', “', '注释：英文著录中篇名前误用全角逗号'),
        ('*', re.compile(r'(?<=[?!])”(?=[A-Z])'), '” ', '注释：后引号后缺空格'),
        ('*', re.compile(r'(?<=[A-Za-z,.;:]) {2,}(?=[A-Za-z0-9])'), ' ', '排版：英文中多余空格'),
    ],
}
