"""Corrections of the ebook text (proof-reading of books 11-15): applied by bk_extract.items(), so the typeset text, the
fidelity counts of bk_report and the font subsets all see the corrected text.

FIXES[scratch] = list of (part, old, new, note)
    part   part number (int) or '*' for every part of the book
    old    literal text (may run across inline runs of one paragraph) -- or re.compile(...) for a pattern
    new    replacement (a pattern's replacement may use \\1 ...)
    note   short reason, listed in docs/16k/corrections.md
A literal fix that matches nothing is reported by bk_report (fix_unused), so a fix can never silently go stale.
"""
import re

CJK = '㐀-䶿一-鿿'
_PUNCT = '，。、；：？！“”‘’（）《》〈〉「」『』…'
# A single em dash between two non-digit characters, one of them Chinese: the ebook's rendering of the Chinese dash '——'
# (ranges such as 1990—2000 or 19世纪—20世纪 keep the single dash; GB/T 15834 uses it as the connector).
DASH1 = re.compile(r'(?<=[%s%s])—(?![—\d])|(?<![—\d])—(?=[%s%s])' % (CJK, _PUNCT, CJK, _PUNCT))

FIXES = {
    'q11': [
        (8, 'RELINK', '我认为，大国总在寻找机会攫取超出其对手的权力', '1', '1', 'part0008#chapter8-ft1', 'part0008#chapter8-fn1',
         '注释：第二章注码1误链到注2，改正'),
    ],
    'q12': [],
    'q13': [
        (range(3, 14), DASH1, '——', '标点：电子书把破折号“——”都排成了单个“—”（578处），一律恢复为“——”；数字间的连接号不动'),
        (range(3, 14), re.compile(r'(?<=\d)~(?=\d)'), '～', '标点：数字范围的半角“~”改为“～”'),
        # copyright page: the ebook lower-cased most Latin capitals
        (1, '（ciP）', '（CIP）', '版权页：电子书把拉丁字母大写误转为小写，恢复（下同）'),
        (1, '图书馆ciP数据', '图书馆CIP数据', '版权页大小写'),
        (1, 'What’s the Right thing to Do?', 'What’s the Right Thing to Do?', '版权页大小写（两处）'),
        (1, 'isBN 978–7–5086–3623–8', 'ISBN 978-7-5086-3623-8', '版权页大小写；ISBN 用连字符（两处）'),
        (1, 'i. ①公… ii. ①桑… ②朱… iii. ①伦理学', 'Ⅰ. ①公… Ⅱ. ①桑… ②朱… Ⅲ. ①伦理学', '版权页：CIP 分类序号为罗马数字'),
        (1, 'Michael J. sandel', 'Michael J. Sandel', '版权页大小写（两处）'),
        (1, 'copyright © 2009', 'Copyright © 2009', '版权页大小写'),
        (1, 'simplified chinese translation copyright © 2011 by china citic Press',
         'Simplified Chinese translation copyright © 2011 by China CITIC Press', '版权页大小写'),
        (1, 'international creative Management, inc.', 'International Creative Management, Inc.', '版权页大小写'),
        (1, 'Bardon-chinese', 'Bardon-Chinese', '版权页大小写'),
        (1, 'ALL RiGHts ReseRVeD', 'ALL RIGHTS RESERVED', '版权页大小写'),
        (1, '（china citic Press）', '（China CITIC Press）', '版权页大小写'),
        (1, '（citic Publishing Group）', '（CITIC Publishing Group）', '版权页大小写'),
        # chapter 1
        (3, '以至于大多数经济学家干脆不予理会。索维尔在', '以至于大多数经济学家干脆不予理会。”索维尔在', '标点：引文缺后引号'),
        (3, '对于反价格欺诈者们的愤慨', '对于价格欺诈者们的愤慨', '多字：愤慨的对象是价格欺诈者（the outrage at price gougers）'),
        (3, '法律是否应当在各种德性观念保持中立', '法律是否应当在各种德性观念之间保持中立', '漏字：在……之间'),
        (3, '（有些是纳税人资助的人寿保险公司）', '（有些靠纳税人的资助才得以维持）',
         '误译：原文 some of them on taxpayer-funded life support，指靠纳税人资金“维持生命”，不是“人寿保险公司”'),
        (3, '成为政府助救的日常用语', '成为政府救助的日常用语', '错字（倒文）：助救→救助'),
        (3, '从自由地角度考量公正', '从自由的角度考量公正', '错字：地→的'),
        (3, '奥萨姆·本·拉登', '奥萨马·本·拉登', '错字：通行译名“奥萨马”'),
        (3, '固定成形，非理性思考能改变', '固定成形，非理性思考所能改变', '漏字：意为“不是理性思考所能改变的”，缺“所”则意思相反'),
        (3, 'Joseph B Treaster', 'Joseph B. Treaster', '注释：英文缩写点脱落（下同）'),
        (3, 'August 18, 2004, pA1;', 'August 18, 2004, p. A1;', '注释：缩写点脱落'),
        (3, 'at wwwcapmagcom/articleasp? ID=3918', 'at www.capmag.com/article.asp?ID=3918', '注释：网址中的点脱落'),
        (3, 'Tyler E Boudreau', 'Tyler E. Boudreau', '注释：缩写点脱落'),
        (3, 'S Mitra Kalita', 'S. Mitra Kalita', '注释：缩写点脱落'),
        (3, '见杰克德·桑蒂斯（Jake DeSantis）', '见杰克·德桑蒂斯（Jake DeSantis）', '注释：人名音译断错（Jake DeSantis）'),
        (3, '与杰克德·桑蒂斯不同', '与杰克·德桑蒂斯不同', '注释：同上'),
        (3, '参议员夏洛特·布朗在这里引证了', '参议员夏洛德·布朗在这里引证了', '注释：与正文译名“夏洛德·布朗”统一'),
        (3, '参议员格拉斯里在爱荷华州的WMT电台', '参议员格拉斯利在艾奥瓦州的WMT电台', '注释：与正文译名“格拉斯利”“艾奥瓦州”统一'),
        (3, 'William D Cohen', 'William D. Cohen', '注释：缩写点脱落'),
        (3, 'David R Francis', 'David R. Francis', '注释：缩写点脱落'),
        (3, 'Marcy 9, 2009', 'March 9, 2009', '注释：月份拼错（Marcy→March）'),
        (3, '.Ibid.', 'Ibid.', '注释：多余的点'),
        # chapter 2
        (4, '被政府和公司普遍采用决策形式', '被政府和公司普遍采用的决策形式', '漏字：的'),
        (4, '交换其他物品和便利设施做法', '交换其他物品和便利设施的做法', '漏字：的'),
        (4, '功利主义的逻辑。他们认为，“如果男子留宿', '功利主义的逻辑。她们认为，“如果男子留宿', '错字：指学院里的年长女教员，他们→她们'),
        (4, '他３岁学希腊语，８岁学拉丁语', '他3岁学希腊语，8岁学拉丁语', '排版：全角数字混入'),
        (4, '即，源于痛苦的快乐和自由是唯一值得追求的目标', '即，快乐和免于痛苦是唯一值得追求的目标',
         '误译：密尔原文 pleasure, and freedom from pain, are the only things desirable as ends'),
        (4, '事物值得拥有的唯一标准就是人们想要他。', '事物值得拥有的唯一标准就是人们想要它。', '错字：指事物，他→它'),
        (4, 'H. L. A Hart, eds.', 'H. L. A. Hart, eds.', '注释：缩写点脱落（下同）'),
        (4, 'John Bowring, ed, The Works', 'John Bowring, ed., The Works', '注释：缩写点脱落'),
        (4, 'Ursula K Le Guin', 'Ursula K. Le Guin', '注释：缩写点脱落'),
        (4, 'Arthur D Little International', 'Arthur D. Little International', '注释：缩写点脱落'),
        (4, 'Philip-Morris-Czech-Studyhtm', 'Philip-Morris-Czech-Study.htm', '注释：网址中的点脱落'),
        (4, 'pmczechstudypdf', 'pmczechstudy.pdf', '注释：网址中的点脱落'),
        (4, 'July 22, 2001, P. D7.', 'July 22, 2001, p. D7.', '注释：页码缩写应小写'),
        (4, '(Cal.Ct. App.1981) The cost-benefit', '(Cal.Ct. App.1981). The cost-benefit', '注释：句末缺点'),
        (4, 'Safety Issues,“ Washington Post', 'Safety Issues,” Washington Post', '注释：后引号误为前引号'),
        (4, 'W. Kip Kiscusi', 'W. Kip Viscusi', '注释：作者名拼错（W. Kip Viscusi）'),
        (4, 'E.P.A Drops the', 'E.P.A. Drops the', '注释：缩写点脱落'),
        # chapter 3: the ebook doubled mark [77] and lost [88]-[90]; every later mark linked one note too early
        (5, 'RELINK', '弗里德曼基于同样的理由反对最低工资制度', '[77]', '[78]', 'part0005#note78f', 'part0005#note78', '注释：注码错位，改为[78]'),
        (5, 'RELINK', '行业执照的要求也错误地干涉', '[78]', '[79]', 'part0005#note79f', 'part0005#note79', '注释：注码错位，改为[79]'),
        (5, 'RELINK', '在《无政府、国家与乌托邦》一书中', '[79]', '[80]', 'part0005#note80f', 'part0005#note80', '注释：注码错位，改为[80]'),
        (5, 'RELINK', '诺齐克反对模式化的公正理论', '[80]', '[81]', 'part0005#note81f', 'part0005#note81', '注释：注码错位，改为[81]'),
        (5, 'RELINK', '由于很多人热切地想看乔丹打球', '[81]', '[82]', 'part0005#note82f', 'part0005#note82', '注释：注码错位，改为[82]'),
        (5, 'RELINK', '那么，向乔丹的收入征税到底错在何处', '[82]', '[83]', 'part0005#note83f', 'part0005#note83', '注释：注码错位，改为[83]'),
        (5, 'RELINK', '获取某个人的劳动成果等同于', '[83]', '[84]', 'part0005#note84f', 'part0005#note84', '注释：注码错位，改为[84]'),
        (5, 'RELINK', '允许买卖肾器官的一个理由', '[84]', '[85]', 'part0005#note85f', 'part0005#note85', '注释：注码错位，改为[85]'),
        (5, 'RELINK', '2007年，79岁的医生杰克·凯沃金', '[85]', '[86]', 'part0005#note86f', 'part0005#note86', '注释：注码错位，改为[86]'),
        (5, 'RELINK', '2001年，在德国罗滕堡的一个村庄', '[86]', '[87]', 'part0005#note87f', 'part0005#note87', '注释：注码错位，改为[87]'),
        (5, 'ADDMARK', '当迈维斯被押受审时', '法庭将迈维斯判为过失杀人并判处八年半的有期徒刑，试图以此来解决这一难题。', '[88]', 'part0005#note88f', 'part0005#note88', '注释：正文漏排注码[88]，补上'),
        (5, 'ADDMARK', '当迈维斯被押受审时', '上诉法院推翻了这一过于宽大的判决，并将迈维斯判为终身监禁。', '[89]', 'part0005#note89f', 'part0005#note89', '注释：正文漏排注码[89]，补上'),
        (5, 'ADDMARK', '当迈维斯被押受审时', '因为他认为工厂化农业经营太不人道了。', '[90]', 'part0005#note90f', 'part0005#note90', '注释：正文漏排注码[90]，补上'),
        (5, 'NOTEBACK', '[87]', 'part0005#note87', '注释：注[87]的返回链接断开，接回'),
        (5, 'NOTEBACK', '[88]', 'part0005#note88', '注释：注[88]的返回链接断开，接回'),
        (5, 'NOTEBACK', '[89]', 'part0005#note89', '注释：注[89]的返回链接断开，接回'),
        (5, 'NOTEBACK', '[90]', 'part0005#note90', '注释：注[90]的返回链接断开，接回'),
        (4, 'Stefan Collini, ed (Cambridge', 'Stefan Collini, ed. (Cambridge', '注释：缩写点脱落'),
        # chapter 3
        (5, '即使是在一个经济较弱的州，成为一个亿万富翁', '即使是在一个经济较弱的年份，成为一个亿万富翁', '误译：福布斯400强是全国榜单，原意是“即使在经济不景气的年份”'),
        (5, '所造成的伤害与跟它对接受者的帮助一样多', '所造成的伤害与它对接受者的帮助一样多', '多字：与跟→与'),
        (5, '阑尾切割手术', '阑尾切除手术', '用词错误：appendectomy 是阑尾切除术'),
        (5, '而非法获得土地或其他资产呢？', '而非法获得土地或其他资产的影响呢？', '漏字：“受到……的影响”句子残缺'),
        (5, '出现在密歇根的一个监狱，因为他八年来一直给那些身患绝症的、想死的病人提供致命性的药物。',
         '走出密歇根的一所监狱，此前他因给那些身患绝症的、想死的病人提供致命性的药物而服刑八年。',
         '误译：凯沃金是2007年服刑八年后获释出狱（emerged from a Michigan prison），不是“出现在监狱”“八年来一直提供药物”'),
        (5, '除了新奥尔良州和华盛顿州之外', '除了俄勒冈州和华盛顿州之外', '事实错误：当时允许医助自杀的是俄勒冈州和华盛顿州（新奥尔良是城市）'),
        (5, '似乎是自由至上主义哲学的一次书面申请', '似乎是自由至上主义哲学的一次教科书式的应用', '误译：textbook application 是“教科书式的应用”，不是“书面申请”'),
        (5, '400 list08_cx_mn_0917richam-ericans_land.html', '400list08_cx_mn_0917richamericans_land.html', '注释：网址被断开'),
        (5, 'Lawrence Michel, Jared Bernstein', 'Lawrence Mishel, Jared Bernstein', '注释：作者名拼错（Lawrence Mishel）'),
        (5, 'www.stateof workingamerica.org', 'www.stateofworkingamerica.org', '注释：网址中多空格'),
        (5, 'concentration. 2004.5.pdf', 'concentration.2004.5.pdf', '注释：网址中多空格'),
        (5, 'Manslaughter,”New York Times', 'Manslaughter,” New York Times', '注释：缺空格'),
        (5, 'Veggie,”Scottish', 'Veggie,” Scottish', '注释：缺空格'),
        (5, 'HEAD', '反驳3：迈克尔·乔丹并非单独作战', 4, '排版：“反驳1”“反驳2”是小标题，“反驳3—5”却排成了正文，统一为小标题'),
        (5, 'HEAD', '反驳4：并不是真的没有经过乔丹本人的同意', 4, '排版：同上'),
        (5, 'HEAD', '反驳5：乔丹很幸运', 4, '排版：同上'),
        # chapter 4
        (6, '最著名的是1863年6月纽约市的征兵暴乱', '最著名的是1863年7月纽约市的征兵暴乱', '事实错误：纽约征兵暴乱发生在1863年7月13—16日'),
        (6, '审判员并不只是投票', '陪审员并不只是投票', '错字：上下文讲的是陪审员'),
        (6, '时，并不真正自愿的，因为她并没有得到充分的信息', '时，并不是真正自愿的，因为她并没有得到充分的信息', '漏字：是'),
        (6, '引发了一个与条件有关问题', '引发了一个与条件有关的问题', '漏字：的'),
        (6, '伊曼努尔·康德', '伊曼纽尔·康德', '译名统一：全书作“伊曼纽尔”'),
        (6, '在选择代孕者时“更加具有歧视性”', '在选择代孕者时“更加挑剔”', '误译：more discriminating 指挑选得更精细，不是“歧视”'),
        (6, 'ADDMARK', '然而，这种全球化的怀孕外包同样也凸显了', '我现在比我怀自己的孩子的时候还要小心。”', '[151]', 'part0006#note151f', 'part0006#note151',
         '注释：正文漏排注码[151]（注151“Ibid.”承注150，指多蒂娅的这句话），补上'),
        (6, 'NOTEBACK', '[151]', 'part0006#note151', '注释：注[151]的返回链接断开，接回'),
        (6, 'James M McPherson', 'James M. McPherson', '注释：缩写点脱落（下同）'),
        (6, 'Geary, We Need. Men', 'Geary, We Need Men', '注释：书名中多点'),
        (6, 'Jeffrey M Jones', 'Jeffrey M. Jones', '注释：缩写点脱落'),
        (6, 'document.php? id=532', 'document.php?id=532', '注释：网址中多空格'),
        (6, 'David M Kennedy', 'David M. Kennedy', '注释：缩写点脱落（两处）'),
        (6, 'Peter W Singer', 'Peter W. Singer', '注释：缩写点脱落'),
        (6, '截止到2008年4月', '截至2008年4月', '用词：表示“到某时为止”用“截至”'),
        (6, 'March Hosenball', 'Mark Hosenball', '注释：作者名拼错（Mark Hosenball）'),
        (6, 'Elizabeth S Anderson', 'Elizabeth S. Anderson', '注释：缩写点脱落'),
        (6, 'Debora L Spar', 'Debora L. Spar', '注释：缩写点脱落'),
        (6, '丝芭自此成为伯纳德学院的院长', '斯帕自此成为伯纳德学院的院长', '注释：译名与正文“斯帕”统一'),
        # chapter 5
        (7, '他发表了第一本著作', '他发表了第一部重要著作', '事实错误：《纯粹理性批判》是康德第一部重要著作（his first major work），此前他已出版多部著作'),
        (7, '纽约商业促进进会', '纽约商业促进会', '多字：促进进会→促进会'),
        (7, '商业改进局经常会在《纽约时报》上', '商业促进会经常会在《纽约时报》上', '译名统一：同段前后作“商业促进会”（Better Business Bureau）'),
        (7, '将理性称为“对欲望的寻求”', '将理性称为“欲望的侦察兵”', '误译：霍布斯称思想为欲望的“侦察兵”（scout for the desires）'),
        (7, '都是与绝对命令想抵触的', '都是与绝对命令相抵触的', '错字：想→相'),
        (7, '可是它们都不是真实的。', '可是它们仍然是真实的。',
         '误译（意思反了）：这些客套话与善意的谎言一样会让人误会，但仍是真话（下文即以“真实而具有误导性的表达”与谎言对照）'),
        (7, '而这位共和党的检察官和克林顿的辩护人', '而这位共和党的国会议员和克林顿的辩护人', '误译：英格利斯是国会议员（上文“一名共和党的国会议员”），不是检察官'),
        (7, '一个带有令人困惑的偏执的社会契约', '一个带有令人困惑的转折的社会契约', '误译：a puzzling twist 是“令人困惑的转折”，不是“偏执”'),
        (7, 'Hackettt Publishing', 'Hackett Publishing', '注释：出版社名多一个t'),
        (7, 'James W Ellington', 'James W. Ellington', '注释：缩写点脱落'),
        # chapter 6
        (8, '只有那些自然公民', '只有那些入籍公民', '误译：宣誓效忠宪法才获得公民身份的是入籍公民（naturalized citizens），“自然公民”意思正相反'),
        (8, 'RENUM', -1, lambda n: 'part0008' if n <= 224 else 'part0009', '{part}#note{n}f', 'part0008#note{n}',
         '注释：第六章全部注码比注文大1（如洛克“默认同意”一句标成了注200《正义论》），整章减1，链接随之改正'),
        (8, 'NOTEBACK', '[199]', 'part0008#note199', '注释：注[199]的返回链接断开，接回'),
        (9, 'RENUM', -2, lambda n: 'part0009', '{part}#note{n}f', 'part0009#note{n}',
         '注释：第七章全部注码比注文大2（如霍普伍德案事实标成了注227），整章减2，链接随之改正'),
        (9, 'NOTEBACK', '[225]', 'part0009#note225', '注释：注[225]的返回链接改指第七章'),
        (9, 'NOTEBACK', '[226]', 'part0009#note226', '注释：注[226]的返回链接断开，接回'),
        (8, '包括意识自由和思想自由的权利', '包括良心自由和思想自由的权利', '误译：liberty of conscience 是“良心自由”'),
        (8, '因为他们根据出生的偶然性来分配收入', '因为它们根据出生的偶然性来分配收入', '代词：指“这些体制”，他们→它们'),
        (8, '他们保证公民们能够得到平等的基本自由', '它们保证公民们能够得到平等的基本自由', '代词：指“市场社会”，他们→它们'),
        (8, '约翰·罗伯特（John Robert）', '约翰·罗伯茨（John Roberts）', '人名错误：美国首席大法官 John Roberts'),
        (8, '首席大法官罗伯特高出100倍', '首席大法官罗伯茨高出100倍', '人名：同上'),
        (8, 'PS. Atiyah', 'P. S. Atiyah', '注释：作者名缩写'),
        (8, '(New York: Oxford University Press, 1979; also', '(New York: Oxford University Press, 1979); also', '注释：缺右括号'),
        (8, 'sAt考试（scholastic Assessment test）', 'SAT考试（Scholastic Assessment Test）', '译注：大小写误转'),
        # chapter 7
        (9, '得克萨斯州立大学法学院运用了', '得克萨斯大学法学院运用了', '名称错误：霍普伍德申请的是得克萨斯大学（University of Texas）法学院，上文即作“得克萨斯大学法学院”'),
        (9, '迈克尔·夏洛特（Michael Charlot），是当时得克萨斯州立大学法学院的主任',
         '迈克尔·沙洛特（Michael Sharlot），是当时得克萨斯大学法学院的院长', '注释：人名、校名与正文统一（Michael Sharlot，得克萨斯大学法学院院长）'),
        (9, '罗纳德·德沃金（Ronald Dwokin）', '罗纳德·德沃金（Ronald Dworkin）', '人名拼错：Dworkin'),
        (9, '在反歧视行为政策中运用民族偏好', '在反歧视行动政策中运用民族偏好', '术语统一：affirmative action 全书作“反歧视行动”'),
        (9, '“斯韦特诉佩因特案” （1950）', '“斯韦特诉佩因特案”（1950）', '排版：多余空格'),
        (9, 'William A Honan', 'William A. Honan', '注释：缩写点脱落'),
        (9, 'Michael J Sandel, Liberalism', 'Michael J. Sandel, Liberalism', '注释：缩写点脱落'),
        (9, '杰弗逊·莫里（ Jefferson Morley ）', '杰弗逊·莫里（Jefferson Morley）', '注释：多余空格'),
        # chapter 8
        (10, '“建立政党是为了什么？”', '“建立城邦是为了什么？”', '误译：亚里士多德问的是城邦（政治共同体）的目的，不是“政党”'),
        (10, '否则，一种政党就沦为一个单纯的联盟', '否则，一种政治联合就沦为一个单纯的联盟', '误译：同上（political association）'),
        (10, '以上两者都忽视了政党的最高目的', '以上两者都忽视了政治联合的最高目的', '误译：同上'),
        (10, '也就是达到这一目的手段', '也就是达到这一目的的手段', '漏字：的'),
        (10, '安东宁·斯科利亚（Antonin Scalia）', '安东宁·斯卡利亚（Antonin Scalia）', '译名统一：下文均作“斯卡利亚”'),
        (10, '以下是25岁的美国高尔夫球职业联赛的老手汤姆·凯特（Tom Kite）', '以下是在美国高尔夫球职业联赛征战了25年的老将汤姆·凯特（Tom Kite）',
         '误译：a 25-year veteran of the PGA Tour 指征战25年，凯特当时已年近五十'),
        (10, 'A. A Milne', 'A. A. Milne', '注释：缩写点脱落'),
        (10, 'Ibid. [1003b].', 'Ibid. [1103b].', '注释：贝克尔页码误为1003b（《尼各马可伦理学》第二卷第一章在1103a—b）'),
        (10, '伯纳德·威廉斯 (Bernard Williams)', '伯纳德·威廉斯（Bernard Williams）', '注释：括号格式'),
        # chapter 9
        (11, '1977年，一个澳大利亚的人权委员会', '1997年，一个澳大利亚的人权委员会',
         '事实错误：关于“被偷的一代”的《带他们回家》报告发表于1997年（下文时任总理霍华德1996年起执政）'),
        (11, '任何人都能遣责不公正的行为', '任何人都能谴责不公正的行为', '错字：遣→谴'),
        (11, '对于道德自由主义者而言，自由就意味着', '对于道德个人主义者而言，自由就意味着', '术语错误：上文定义的是“道德个人主义”'),
        (11, '我所做出一个选择、一个承诺', '我所做出的一个选择、一个承诺', '漏字：的'),
        (11, '身份、登记、习俗、传统', '身份、等级、习俗、传统', '错字：登记→等级（rank）'),
        (11, '它追求某种功利或连贯性', '它追求某种统一性或连贯性', '误译：麦金泰尔说的是 unity or coherence（统一性或连贯性），不是“功利”'),
    ],
    'q14': [
        (5, '40074千米（地球的直径）', '40074千米（地球的周长）', '事实错误：40074千米是赤道周长（地球直径约12742千米）'),
        (6, '世界各国政府答成共识', '世界各国政府达成共识', '错字：答成→达成'),
        (6, '所以水蒸气就会冷凝成气溶胶，形成云', '所以水蒸气就会在气溶胶上冷凝，形成云',
         '误译：水汽以气溶胶为凝结核冷凝成云（上段即说“没有这些微小的颗粒，水蒸气就不能凝结成云”）'),
        (6, 'MOVE', '哈德来环流、费雷尔环流和极地环流', '如前文所述，地球的形状', '排版：小标题被错置在图6与方框1之前，移回其正文之前'),
        (7, '强烈的信风推动风暴向南拖过美国中部', '强烈的信风推动风暴向南拖过中美洲', '误译：“米奇”飓风登陆的是中美洲（洪都拉斯等，见第四章），不是美国中部'),
        (7, '强烈的西风和洋流使其保持在那里', '强烈的西向风和西向洋流使其保持在那里',
         '误译：把暖池推在西太平洋的是自东向西吹的信风；“西风”是自西吹来的风，方向正相反'),
        (7, '西风和洋流得到增强', '西向风和洋流得到增强', '误译：同上（拉尼娜时期增强的是西向的信风）'),
        (7, '大气——海洋环流模型（AOGCMs）', '大气—海洋环流模型（AOGCMs）', '标点：复合名称用连接号“—”，与下文“大气—海洋环流模型”一致'),
        (8, '75％～80%', '75%～80%', '符号：全角、半角百分号混用'),
        (9, '大约400万年后关闭的巴拿马通道', '大约400万年前关闭的巴拿马通道',
         '事实错误：巴拿马通道约400万年前关闭（上文：北大西洋深层水“可能只有400万年的历史”）'),
        (11, '冰雪不断积累，反照，即反射回空间的阳光就会增加', '冰雪不断积累，反照率，即反射回空间的阳光就会增加', '漏字：反照→反照率（同段下文即作“反照率”）'),
        (11, '劳伦泰德河和密西西比河的河道', '圣劳伦斯河和密西西比河的河道', '误译：并无“劳伦泰德河”（劳伦泰德是冰盖名），排泄其融水的是圣劳伦斯河'),
        (11, '随着海洋降低，连接相邻各大陆', '随着海平面降低，连接相邻各大陆', '漏字：海洋→海平面'),
        (12, '包括太阳光斑和火山爆发', '包括太阳黑子和火山爆发', '误译：与火山并列的自然因素是太阳黑子（太阳活动周期）'),
        (13, '每个楔子每年可封存约10亿兆吨的碳', '每个楔子每年可封存约10亿吨的碳', '量级错误（多字）：一个“楔子”为每年10亿吨碳（同章下文“另一个每年10亿吨的楔子”）'),
        (13, '生物碳酸盐', '碳酸氢盐', '误译：HCO₃⁻是碳酸氢根（bicarbonate），不是“生物碳酸盐”（两处）'),
        (13, '一场雪崩把湖水混杂在一起', '一场山崩把湖水混杂在一起', '误译：喀麦隆尼奥斯湖一带无积雪，触发湖水翻涌的是山崩（滑坡）'),
        (14, '正常的冰期——间冰期旋回', '正常的冰期—间冰期旋回', '标点：复合名称用连接号，与全书“冰期—间冰期旋回”一致'),
        (14, '南极洲——澳大利亚大陆', '南极洲—澳大利亚大陆', '标点：复合名称用连接号'),
        (15, '生物群的标本化和多样化', '生物群的物种形成和多样化', '误译：避难所理论讲的是物种形成（speciation），不是“标本化”'),
    ],
    'q15': [],
}
